// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Nov 20 14:29:56 2024
// from snax_req_handler.cc

`timescale 1ps / 1ps


module snax_req_handler_N_Muxb_1_2_24_4( in2, ctrl1, out1 );

    input in2;
    input ctrl1;
    output out1;
    reg out1;

    
    // rtl_process:snax_req_handler_N_Muxb_1_2_24_4/snax_req_handler_N_Muxb_1_2_24_4_thread_1
    always @*
      begin : snax_req_handler_N_Muxb_1_2_24_4_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = 1'b0;
            end
        endcase
      end

endmodule




