// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 21:17:58 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Add_5U_107_4( in1, out1 );

    input [3:0] in1;
    output [4:0] out1;

    
    // rtl_process:qkv_macro_handler_hub_Add_5U_107_4/qkv_macro_handler_hub_Add_5U_107_4_thread_1
    assign out1 = {1'b0, in1} + 5'd01;

endmodule


