// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 21:17:57 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Sub_32S_2_4( in1, out1 );

    input [31:0] in1;
    output [31:0] out1;

    
    // rtl_process:qkv_macro_handler_hub_Sub_32S_2_4/qkv_macro_handler_hub_Sub_32S_2_4_thread_1
    assign out1 = in1 - 32'd0000000001;

endmodule

