// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Jan 29 09:52:59 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_N_Mux_1_2_84_4( in2, ctrl1, out1 );

    input in2;
    input ctrl1;
    output out1;
    reg out1;

    
    // rtl_process:qkv_macro_handler_unit_N_Mux_1_2_84_4/qkv_macro_handler_unit_N_Mux_1_2_84_4_thread_1
    always @*
      begin : qkv_macro_handler_unit_N_Mux_1_2_84_4_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = 1'b1;
            end
        endcase
      end

endmodule




