// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Sep 30 18:33:28 2024
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_8U_142_4( in1, out1 );

    input [7:0] in1;
    output [7:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_8U_145_4/qkv_macro_handler_unit_Add_8U_145_4_thread_1
    assign out1 = in1 + 8'd001;

endmodule




