// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Oct  1 17:46:33 2024
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_10U_159_4( in1, out1 );

    input [9:0] in1;
    output [9:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_10U_159_4/qkv_macro_handler_unit_Add_10U_159_4_thread_1
    assign out1 = in1 + 10'd0001;

endmodule


