// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Nov 20 14:32:38 2024
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Equal_1U_75_4( in1, out1 );

    input [5:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_hub_Equal_1U_104_4/qkv_macro_handler_hub_Equal_1U_104_4_thread_1
    assign out1 = in1 == 6'd54;

endmodule




