// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 17:12:21 2025
// from snax_req_handler.cc

`timescale 1ps / 1ps


module snax_req_handler_Or_1Ux1U_1U_s_1( in2, in1, out1 );

    input in2;
    input in1;
    output out1;

    
    // rtl_process:snax_req_handler_Or_1Ux1U_1U_s_1/snax_req_handler_Or_1Ux1U_1U_s_1_thread_1
    assign out1 = in2 | in1;

endmodule

