// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Oct 17 11:13:52 2024
// from snax_req_handler.cc

`timescale 1ps / 1ps


module snax_req_handler_Equal_32Ux4U_1U_1( in2, in1, out1 );

    input [31:0] in2;
    input [3:0] in1;
    output out1;

    
    // rtl_process:snax_req_handler_Equal_32Ux4U_1U_1/snax_req_handler_Equal_32Ux4U_1U_1_thread_1
    assign out1 = in2 == {28'b0000000000000000000000000000, in1};

endmodule

