// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Oct 17 11:13:52 2024
// from snax_req_handler.cc

`timescale 1ps / 1ps


module snax_req_handler_N_Mux_8_2_24_1( in2, ctrl1, out1 );

    input [7:0] in2;
    input ctrl1;
    output [7:0] out1;
    reg [7:0] out1;

    
    // rtl_process:snax_req_handler_N_Mux_8_2_24_1/snax_req_handler_N_Mux_8_2_24_1_thread_1
    always @*
      begin : snax_req_handler_N_Mux_8_2_24_1_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = 8'd000;
            end
        endcase
      end

endmodule

