// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Oct  1 17:40:09 2024
// from snax_req_handler.cc

`timescale 1ps / 1ps


module snax_req_handler_OrReduction_32U_1U_1( in1, out1 );

    input [31:0] in1;
    output out1;

    
    // rtl_process:snax_req_handler_OrReduction_32U_1U_1/snax_req_handler_OrReduction_32U_1U_1_thread_1
    assign out1 = (|in1);

endmodule

