// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Jan 30 22:15:01 2025
// from snax_req_handler.cc

`timescale 1ps / 1ps


module snax_req_handler_Not_1U_1U_s_4( in1, out1 );

    input in1;
    output out1;

    
    // rtl_process:snax_req_handler_Not_1U_1U_s_4/snax_req_handler_Not_1U_1U_s_4_thread_1
    assign out1 = !in1;

endmodule


