// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 17:18:06 2025
// from snax_req_handler.cc

`timescale 1ps / 1ps


module snax_req_handler_Add_5U_52_4( in1, out1 );

    input [4:0] in1;
    output [4:0] out1;

    
    // rtl_process:snax_req_handler_Add_5U_52_4/snax_req_handler_Add_5U_52_4_thread_1
    assign out1 = in1 + 5'd01;

endmodule

