// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 13:05:37 2025
// from snax_req_handler.cc

`timescale 1ps / 1ps


module snax_req_handler_Equal_1U_41_4( in1, out1 );

    input [31:0] in1;
    output out1;

    
    // rtl_process:snax_req_handler_Equal_1U_41_4/snax_req_handler_Equal_1U_41_4_thread_1
    assign out1 = in1 == 32'd0000000017;

endmodule


