// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Oct 10 15:46:45 2024
// from snax_req_handler.cc

`timescale 1ps / 1ps


module snax_req_handler_Not_1U_1U_s_1( in1, out1 );

    input in1;
    output out1;

    
    // rtl_process:snax_req_handler_Not_1U_1U_s_1/snax_req_handler_Not_1U_1U_s_1_thread_1
    assign out1 = !in1;

endmodule

