// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Jan 30 22:15:01 2025
// from snax_req_handler.cc

`timescale 1ps / 1ps


module snax_req_handler_Or_1Ux1U_1U_4( in2, in1, out1 );

    input in2;
    input in1;
    output out1;

    
    // rtl_process:snax_req_handler_Or_1Ux1U_1U_4/snax_req_handler_Or_1Ux1U_1U_4_thread_1
    assign out1 = in2 | in1;

endmodule


