// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 17:18:04 2025
// from snax_req_handler.cc

`timescale 1ps / 1ps


module snax_req_handler_Equal_32Ux5U_1U_4( in2, in1, out1 );

    input [31:0] in2;
    input [4:0] in1;
    output out1;

    
    // rtl_process:snax_req_handler_Equal_32Ux5U_1U_4/snax_req_handler_Equal_32Ux5U_1U_4_thread_1
    assign out1 = in2 == {27'b000000000000000000000000000, in1};

endmodule

