// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 12:06:55 2025
// from snax_req_handler.cc

`timescale 1ps / 1ps


module snax_req_handler_Or_1Ux1U_1U_s_4( in2, in1, out1 );

    input in2;
    input in1;
    output out1;

    
    // rtl_process:snax_req_handler_Or_1Ux1U_1U_s_4/snax_req_handler_Or_1Ux1U_1U_s_4_thread_1
    assign out1 = in2 | in1;

endmodule


