// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Feb  4 21:37:17 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_Add_6U_2_1( in1, out1 );

    input [4:0] in1;
    output [5:0] out1;

    
    // rtl_process:streamer_handler_Add_6U_2_1/streamer_handler_Add_6U_2_1_thread_1
    assign out1 = {1'b0, in1} + 6'd01;

endmodule

