// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 12:07:31 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_N_Muxb_1_2_3_4( in2, ctrl1, out1 );

    input in2;
    input ctrl1;
    output out1;
    reg out1;

    
    // rtl_process:streamer_handler_N_Muxb_1_2_3_4/streamer_handler_N_Muxb_1_2_3_4_thread_1
    always @*
      begin : streamer_handler_N_Muxb_1_2_3_4_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = 1'b1;
            end
          default: 
            begin
              out1 = in2;
            end
        endcase
      end

endmodule


