// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Jan 30 14:42:34 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_LessThan_1U_6_4( in1, out1 );

    input [7:0] in1;
    output out1;

    
    // rtl_process:streamer_handler_LessThan_1U_6_4/streamer_handler_LessThan_1U_6_4_thread_1
    assign out1 = (in1[7] ^ in1 < 8'd064);

endmodule


