// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Feb  5 10:00:43 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_N_MuxB_512_2_23_1( in3, in2, ctrl1, out1 );

    input [511:0] in3;
    input [511:0] in2;
    input ctrl1;
    output [511:0] out1;
    reg [511:0] out1;

    
    // rtl_process:streamer_handler_N_MuxB_512_2_23_1/streamer_handler_N_MuxB_512_2_23_1_thread_1
    always @*
      begin : streamer_handler_N_MuxB_512_2_23_1_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in3;
            end
        endcase
      end

endmodule

