// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Oct 30 16:09:28 2024
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_N_Mux_1_2_2_4( in3, in2, ctrl1, out1 );

    input in3;
    input in2;
    input ctrl1;
    output out1;
    reg out1;

    
    // rtl_process:streamer_handler_N_Mux_1_2_2_4/streamer_handler_N_Mux_1_2_2_4_thread_1
    always @*
      begin : streamer_handler_N_Mux_1_2_2_4_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in3;
            end
        endcase
      end

endmodule


