// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Oct 17 11:14:29 2024
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_Add_2Ux1U_3U_1( in2, in1, out1 );

    input [1:0] in2;
    input in1;
    output [2:0] out1;

    
    // rtl_process:streamer_handler_Add_2Ux1U_3U_1/streamer_handler_Add_2Ux1U_3U_1_thread_1
    assign out1 = {1'b0, in2} + {2'b00, in1};

endmodule

