// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Feb  6 10:35:33 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_And_1Ux1U_1U_s_4( in2, in1, out1 );

    input in2;
    input in1;
    output out1;

    
    // rtl_process:streamer_handler_And_1Ux1U_1U_s_4/streamer_handler_And_1Ux1U_1U_s_4_thread_1
    assign out1 = in2 & in1;

endmodule


