// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Oct 17 11:14:29 2024
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_LessThan_1U_11_4( in1, out1 );

    input [5:0] in1;
    output out1;

    
    // rtl_process:streamer_handler_LessThan_1U_11_4/streamer_handler_LessThan_1U_11_4_thread_1
    assign out1 = (in1[5] ^ in1 < 6'd16);

endmodule

