// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Feb  4 13:10:35 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_LessThan_1U_2_4( in1, out1 );

    input [2:0] in1;
    output out1;

    
    // rtl_process:streamer_handler_LessThan_1U_2_4/streamer_handler_LessThan_1U_2_4_thread_1
    assign out1 = (in1[2] ^ in1 < 3'd2);

endmodule

