// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 13:20:40 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_Add_7U_4_1( in1, out1 );

    input [5:0] in1;
    output [6:0] out1;

    
    // rtl_process:streamer_handler_Add_7U_4_1/streamer_handler_Add_7U_4_1_thread_1
    assign out1 = {1'b0, in1} + 7'd001;

endmodule

