// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Feb  4 21:37:17 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_Add_5Ux1U_6U_1( in2, in1, out1 );

    input [4:0] in2;
    input in1;
    output [5:0] out1;

    
    // rtl_process:streamer_handler_Add_5Ux1U_6U_1/streamer_handler_Add_5Ux1U_6U_1_thread_1
    assign out1 = {1'b0, in2} + {5'b00000, in1};

endmodule

