// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 12:34:51 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_Add_5U_8_1( in1, out1 );

    input [3:0] in1;
    output [4:0] out1;

    
    // rtl_process:streamer_handler_Add_5U_8_1/streamer_handler_Add_5U_8_1_thread_1
    assign out1 = {1'b0, in1} + 5'd01;

endmodule

