// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Jan 29 09:42:52 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_LessThan_6Sx6S_1U_1( in2, in1, out1 );

    input [5:0] in2;
    input [5:0] in1;
    output out1;

    
    // rtl_process:streamer_handler_LessThan_6Sx6S_1U_1/streamer_handler_LessThan_6Sx6S_1U_1_thread_1
    assign out1 = (in2 < in1 ^ (in1[5] ^ in2[5]));

endmodule

