// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Oct 30 16:09:28 2024
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_LessThan_1U_9_1( in1, out1 );

    input [2:0] in1;
    output out1;

    
    // rtl_process:streamer_handler_LessThan_1U_9_1/streamer_handler_LessThan_1U_9_1_thread_1
    assign out1 = (in1[2] ^ in1 < 3'd3);

endmodule

