// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Oct 30 16:09:28 2024
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_LessThan_4Sx4S_1U_1( in2, in1, out1 );

    input [3:0] in2;
    input [3:0] in1;
    output out1;

    
    // rtl_process:streamer_handler_LessThan_4Sx4S_1U_1/streamer_handler_LessThan_4Sx4S_1U_1_thread_1
    assign out1 = (in2 < in1 ^ (in1[3] ^ in2[3]));

endmodule

