// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 15:52:54 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_Not_1U_1U_4( in1, out1 );

    input in1;
    output out1;

    
    // rtl_process:streamer_handler_Not_1U_1U_4/streamer_handler_Not_1U_1U_4_thread_1
    assign out1 = !in1;

endmodule


