// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 12:39:07 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_Add_1Ux1U_2U_1( in2, in1, out1 );

    input in2;
    input in1;
    output [1:0] out1;

    
    // rtl_process:streamer_handler_Add_1Ux1U_2U_1/streamer_handler_Add_1Ux1U_2U_1_thread_1
    assign out1 = {1'b0, in2} + {1'b0, in1};

endmodule

