// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 17:12:57 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_LessThan_1U_0_4( in1, out1 );

    input [3:0] in1;
    output out1;

    
    // rtl_process:streamer_handler_LessThan_1U_0_4/streamer_handler_LessThan_1U_0_4_thread_1
    assign out1 = (in1[3] ^ in1 < 4'd04);

endmodule

