// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 18:51:00 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_Add_2U_5_1( in1, out1 );

    input in1;
    output [1:0] out1;

    
    // rtl_process:streamer_handler_Add_2U_5_1/streamer_handler_Add_2U_5_1_thread_1
    assign out1 = {1'b0, in1} + 2'd1;

endmodule

