// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Oct 30 16:09:34 2024
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_Add_6U_14_4( in1, out1 );

    input [5:0] in1;
    output [5:0] out1;

    
    // rtl_process:streamer_handler_Add_6U_14_4/streamer_handler_Add_6U_14_4_thread_1
    assign out1 = in1 + 6'd01;

endmodule

