// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Feb  4 21:37:17 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_Add_3U_5_1( in1, out1 );

    input [1:0] in1;
    output [2:0] out1;

    
    // rtl_process:streamer_handler_Add_3U_5_1/streamer_handler_Add_3U_5_1_thread_1
    assign out1 = {1'b0, in1} + 3'd1;

endmodule

