// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Feb  4 18:32:22 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_Add_6Ux1U_7U_4( in2, in1, out1 );

    input [5:0] in2;
    input in1;
    output [6:0] out1;

    
    // rtl_process:streamer_handler_Add_6Ux1U_7U_4/streamer_handler_Add_6Ux1U_7U_4_thread_1
    assign out1 = {1'b0, in2} + {6'b000000, in1};

endmodule

