// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 12:55:30 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_N_Mux_8_4_15_4( in5, in4, in3, in2, ctrl1, out1 );

    input [7:0] in5;
    input [7:0] in4;
    input [7:0] in3;
    input [7:0] in2;
    input [1:0] ctrl1;
    output [7:0] out1;
    reg [7:0] out1;

    
    // rtl_process:streamer_handler_N_Mux_8_4_15_4/streamer_handler_N_Mux_8_4_15_4_thread_1
    always @*
      begin : streamer_handler_N_Mux_8_4_15_4_thread_1
        case (ctrl1) 
          2'd2: 
            begin
              out1 = in4;
            end
          2'd1: 
            begin
              out1 = in3;
            end
          2'd0: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in5;
            end
        endcase
      end

endmodule


