// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 18:51:06 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_Add_8U_24_4( in1, out1 );

    input [7:0] in1;
    output [7:0] out1;

    
    // rtl_process:streamer_handler_Add_8U_24_4/streamer_handler_Add_8U_24_4_thread_1
    assign out1 = in1 + 8'd001;

endmodule

