// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Feb  4 15:01:06 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_LessThan_1U_1_1( in1, out1 );

    input [2:0] in1;
    output out1;

    
    // rtl_process:streamer_handler_LessThan_1U_1_1/streamer_handler_LessThan_1U_1_1_thread_1
    assign out1 = (in1[2] ^ in1 < 3'd3);

endmodule

