// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 14:01:12 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_N_Muxb_1_2_105_1( in3, in2, ctrl1, out1 );

    input in3;
    input in2;
    input ctrl1;
    output out1;
    reg out1;

    
    // rtl_process:qkt_macro_handler_unit_N_Muxb_1_2_105_1/qkt_macro_handler_unit_N_Muxb_1_2_105_1_thread_1
    always @*
      begin : qkt_macro_handler_unit_N_Muxb_1_2_105_1_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in3;
            end
        endcase
      end

endmodule


