// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 21:28:04 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_LessThan_4Sx4S_1U_1( in2, in1, out1 );

    input [3:0] in2;
    input [3:0] in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_hub_LessThan_4Sx4S_1U_1/qkt_macro_handler_hub_LessThan_4Sx4S_1U_1_thread_1
    assign out1 = (in2 < in1 ^ (in1[3] ^ in2[3]));

endmodule

