// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 16:52:27 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_LessThan_1U_51_4( in1, out1 );

    input [7:0] in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_hub_LessThan_1U_51_4/qkt_macro_handler_hub_LessThan_1U_51_4_thread_1
    assign out1 = (in1[7] ^ in1 < 8'd064);

endmodule


