// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 22:51:47 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Sub_27Sx17U_28S_1( in2, in1, out1 );

    input [26:0] in2;
    input [16:0] in1;
    output [27:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Sub_27Sx17U_28S_1/qkt_macro_handler_unit_Sub_27Sx17U_28S_1_thread_1
    assign out1 = {in2[26], in2} - {11'b00000000000, in1};

endmodule

