// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Nov 20 15:38:09 2024
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Or_56Ux52U_56U_4( in2, in1, out1 );

    input [55:0] in2;
    input [51:0] in1;
    output [55:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Or_56Ux52U_56U_4/qkv_macro_handler_unit_Or_56Ux52U_56U_4_thread_1
    assign out1 = in2 | {4'b0000, in1};

endmodule




