// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 12:06:26 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Not_1U_1U_s_1( in1, out1 );

    input in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_hub_Not_1U_1U_s_1/qkv_macro_handler_hub_Not_1U_1U_s_1_thread_1
    assign out1 = !in1;

endmodule


