// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Oct 30 16:10:55 2024
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Equal_5Ux2U_1U_4( in2, in1, out1 );

    input [4:0] in2;
    input [1:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_hub_Equal_5Ux2U_1U_4/qkv_macro_handler_hub_Equal_5Ux2U_1U_4_thread_1
    assign out1 = in2 == {3'b000, in1};

endmodule

