// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 13:09:35 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_gen_busy_r_4( in1, in2, in3, out1 );

    input in1;
    input in2;
    input in3;
    output [2:0] out1;
    wire  ioread003;
    wire  tmp1095;
    wire  ioread004;
    wire  tmp1096;
    wire  tmp1097;
    wire  tmp1098;
    wire  tmp1099;
    wire  tmp1100;
    wire  conv_kernel_qkv_in_gen_busy_conv_kernel_qkv_in_m_data_is_invalid_next;
    wire  gdiv;
    wire  gnew_req;
    wire  tmp1103;
    wire  tmp1102;
    wire  tmp1101;

    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_4/qkv_macro_handler_hub_gen_busy_r_4_thread_1_p16
    assign out1 = {tmp1103, {tmp1102, tmp1101}};
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_4/qkv_macro_handler_hub_gen_busy_r_4_thread_1_p15
    assign tmp1103 = gnew_req;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_4/qkv_macro_handler_hub_gen_busy_r_4_thread_1_p14
    assign tmp1102 = gdiv;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_4/qkv_macro_handler_hub_gen_busy_r_4_thread_1_p13
    assign tmp1101 = conv_kernel_qkv_in_gen_busy_conv_kernel_qkv_in_m_data_is_invalid_next;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_4/qkv_macro_handler_hub_gen_busy_r_4_thread_1_p12
    assign conv_kernel_qkv_in_gen_busy_conv_kernel_qkv_in_m_data_is_invalid_next = tmp1100;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_4/qkv_macro_handler_hub_gen_busy_r_4_thread_1_p11
    assign tmp1100 = ~gdiv;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_4/qkv_macro_handler_hub_gen_busy_r_4_thread_1_p10
    assign gdiv = in1 & tmp1099;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_4/qkv_macro_handler_hub_gen_busy_r_4_thread_1_p9
    assign tmp1099 = tmp1098;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_4/qkv_macro_handler_hub_gen_busy_r_4_thread_1_p8
    assign tmp1098 = ~tmp1097;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_4/qkv_macro_handler_hub_gen_busy_r_4_thread_1_p7
    assign tmp1097 = gnew_req;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_4/qkv_macro_handler_hub_gen_busy_r_4_thread_1_p6
    assign gnew_req = ioread004 & tmp1096;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_4/qkv_macro_handler_hub_gen_busy_r_4_thread_1_p5
    assign tmp1096 = ioread003 | tmp1095;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_4/qkv_macro_handler_hub_gen_busy_r_4_thread_1_p4
    assign tmp1095 = in1;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_4/qkv_macro_handler_hub_gen_busy_r_4_thread_1_p3
    assign ioread004 = in2;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_4/qkv_macro_handler_hub_gen_busy_r_4_thread_1_p2
    assign ioread003 = in3;

endmodule


