// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 12:41:44 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_N_Muxb_1_16_166_1( in17, in16, in15, in14, in13, in12, in11, in10, in9, in8, in7, in6, in5, in4, in3, in2, ctrl1, out1 );

    input in17;
    input in16;
    input in15;
    input in14;
    input in13;
    input in12;
    input in11;
    input in10;
    input in9;
    input in8;
    input in7;
    input in6;
    input in5;
    input in4;
    input in3;
    input in2;
    input [3:0] ctrl1;
    output out1;
    reg out1;

    
    // rtl_process:qkv_macro_handler_hub_N_Muxb_1_16_166_1/qkv_macro_handler_hub_N_Muxb_1_16_166_1_thread_1
    always @*
      begin : qkv_macro_handler_hub_N_Muxb_1_16_166_1_thread_1
        case (ctrl1) 
          4'd14: 
            begin
              out1 = in16;
            end
          4'd13: 
            begin
              out1 = in15;
            end
          4'd12: 
            begin
              out1 = in14;
            end
          4'd11: 
            begin
              out1 = in13;
            end
          4'd10: 
            begin
              out1 = in12;
            end
          4'd09: 
            begin
              out1 = in11;
            end
          4'd08: 
            begin
              out1 = in10;
            end
          4'd07: 
            begin
              out1 = in9;
            end
          4'd06: 
            begin
              out1 = in8;
            end
          4'd05: 
            begin
              out1 = in7;
            end
          4'd04: 
            begin
              out1 = in6;
            end
          4'd03: 
            begin
              out1 = in5;
            end
          4'd02: 
            begin
              out1 = in4;
            end
          4'd01: 
            begin
              out1 = in3;
            end
          4'd00: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in17;
            end
        endcase
      end

endmodule

