// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 14:51:36 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Add_3U_0_4( in1, out1 );

    input [1:0] in1;
    output [2:0] out1;

    
    // rtl_process:qkv_macro_handler_hub_Add_3U_0_4/qkv_macro_handler_hub_Add_3U_0_4_thread_1
    assign out1 = {1'b0, in1} + 3'd1;

endmodule


