// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Oct 17 11:15:55 2024
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Equal_1U_76_4( in1, out1 );

    input [4:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_hub_Equal_1U_76_4/qkv_macro_handler_hub_Equal_1U_76_4_thread_1
    assign out1 = in1 == 5'd29;

endmodule


