// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Oct 10 15:48:32 2024
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Add_5Sx4U_5S_4( in2, in1, out1 );

    input [4:0] in2;
    input [3:0] in1;
    output [4:0] out1;

    
    // rtl_process:qkv_macro_handler_hub_Add_5Sx4U_5S_4/qkv_macro_handler_hub_Add_5Sx4U_5S_4_thread_1
    assign out1 = in2 + {1'b0, in1};

endmodule

