// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 12:41:44 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Add_6Ux1U_7U_1( in2, in1, out1 );

    input [5:0] in2;
    input in1;
    output [6:0] out1;

    
    // rtl_process:qkv_macro_handler_hub_Add_6Ux1U_7U_1/qkv_macro_handler_hub_Add_6Ux1U_7U_1_thread_1
    assign out1 = {1'b0, in2} + {6'b000000, in1};

endmodule

