// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 15:11:44 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_gen_busy_r_1( in1, in2, in3, out1 );

    input in1;
    input in2;
    input in3;
    output [2:0] out1;
    wire  ioread003;
    wire  tmp1098;
    wire  ioread004;
    wire  tmp1099;
    wire  tmp1100;
    wire  tmp1101;
    wire  tmp1102;
    wire  tmp1103;
    wire  conv_kernel_qkv_in_gen_busy_conv_kernel_qkv_in_m_data_is_invalid_next;
    wire  gdiv;
    wire  gnew_req;
    wire  tmp1106;
    wire  tmp1105;
    wire  tmp1104;

    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_1/qkv_macro_handler_hub_gen_busy_r_1_thread_1_p16
    assign out1 = {tmp1106, {tmp1105, tmp1104}};
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_1/qkv_macro_handler_hub_gen_busy_r_1_thread_1_p15
    assign tmp1106 = gnew_req;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_1/qkv_macro_handler_hub_gen_busy_r_1_thread_1_p14
    assign tmp1105 = gdiv;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_1/qkv_macro_handler_hub_gen_busy_r_1_thread_1_p13
    assign tmp1104 = conv_kernel_qkv_in_gen_busy_conv_kernel_qkv_in_m_data_is_invalid_next;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_1/qkv_macro_handler_hub_gen_busy_r_1_thread_1_p12
    assign conv_kernel_qkv_in_gen_busy_conv_kernel_qkv_in_m_data_is_invalid_next = tmp1103;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_1/qkv_macro_handler_hub_gen_busy_r_1_thread_1_p11
    assign tmp1103 = ~gdiv;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_1/qkv_macro_handler_hub_gen_busy_r_1_thread_1_p10
    assign gdiv = in1 & tmp1102;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_1/qkv_macro_handler_hub_gen_busy_r_1_thread_1_p9
    assign tmp1102 = tmp1101;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_1/qkv_macro_handler_hub_gen_busy_r_1_thread_1_p8
    assign tmp1101 = ~tmp1100;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_1/qkv_macro_handler_hub_gen_busy_r_1_thread_1_p7
    assign tmp1100 = gnew_req;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_1/qkv_macro_handler_hub_gen_busy_r_1_thread_1_p6
    assign gnew_req = ioread004 & tmp1099;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_1/qkv_macro_handler_hub_gen_busy_r_1_thread_1_p5
    assign tmp1099 = ioread003 | tmp1098;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_1/qkv_macro_handler_hub_gen_busy_r_1_thread_1_p4
    assign tmp1098 = in1;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_1/qkv_macro_handler_hub_gen_busy_r_1_thread_1_p3
    assign ioread004 = in2;
    
    // rtl_process:qkv_macro_handler_hub_gen_busy_r_1/qkv_macro_handler_hub_gen_busy_r_1_thread_1_p2
    assign ioread003 = in3;

endmodule

