// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 12:10:02 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_N_Mux_1_32_164_4( in33, in32, in31, in30, in29, in28, in27, in26, in25, in24, in23, in22, in21, in20, in19, in18, in17, in16, in15, in14, in13, in12, in11, in10, in9, in8, in7, in6, in5, in4, in3, in2, ctrl1, out1 );

    input in33;
    input in32;
    input in31;
    input in30;
    input in29;
    input in28;
    input in27;
    input in26;
    input in25;
    input in24;
    input in23;
    input in22;
    input in21;
    input in20;
    input in19;
    input in18;
    input in17;
    input in16;
    input in15;
    input in14;
    input in13;
    input in12;
    input in11;
    input in10;
    input in9;
    input in8;
    input in7;
    input in6;
    input in5;
    input in4;
    input in3;
    input in2;
    input [4:0] ctrl1;
    output out1;
    reg out1;

    
    // rtl_process:qkv_macro_handler_hub_N_Mux_1_32_164_4/qkv_macro_handler_hub_N_Mux_1_32_164_4_thread_1
    always @*
      begin : qkv_macro_handler_hub_N_Mux_1_32_164_4_thread_1
        case (ctrl1) 
          5'd30: 
            begin
              out1 = in32;
            end
          5'd29: 
            begin
              out1 = in31;
            end
          5'd28: 
            begin
              out1 = in30;
            end
          5'd27: 
            begin
              out1 = in29;
            end
          5'd26: 
            begin
              out1 = in28;
            end
          5'd25: 
            begin
              out1 = in27;
            end
          5'd24: 
            begin
              out1 = in26;
            end
          5'd23: 
            begin
              out1 = in25;
            end
          5'd22: 
            begin
              out1 = in24;
            end
          5'd21: 
            begin
              out1 = in23;
            end
          5'd20: 
            begin
              out1 = in22;
            end
          5'd19: 
            begin
              out1 = in21;
            end
          5'd18: 
            begin
              out1 = in20;
            end
          5'd17: 
            begin
              out1 = in19;
            end
          5'd16: 
            begin
              out1 = in18;
            end
          5'd15: 
            begin
              out1 = in17;
            end
          5'd14: 
            begin
              out1 = in16;
            end
          5'd13: 
            begin
              out1 = in15;
            end
          5'd12: 
            begin
              out1 = in14;
            end
          5'd11: 
            begin
              out1 = in13;
            end
          5'd10: 
            begin
              out1 = in12;
            end
          5'd09: 
            begin
              out1 = in11;
            end
          5'd08: 
            begin
              out1 = in10;
            end
          5'd07: 
            begin
              out1 = in9;
            end
          5'd06: 
            begin
              out1 = in8;
            end
          5'd05: 
            begin
              out1 = in7;
            end
          5'd04: 
            begin
              out1 = in6;
            end
          5'd03: 
            begin
              out1 = in5;
            end
          5'd02: 
            begin
              out1 = in4;
            end
          5'd01: 
            begin
              out1 = in3;
            end
          5'd00: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in33;
            end
        endcase
      end

endmodule


