// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Oct  1 17:41:23 2024
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_LessThan_1U_35_4( in1, out1 );

    input [6:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_hub_LessThan_1U_35_4/qkv_macro_handler_hub_LessThan_1U_35_4_thread_1
    assign out1 = (in1[6] ^ in1 < 7'd032);

endmodule

