// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 13:59:36 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Add_2U_150_1( in1, out1 );

    input in1;
    output [1:0] out1;

    
    // rtl_process:qkv_macro_handler_hub_Add_2U_150_1/qkv_macro_handler_hub_Add_2U_150_1_thread_1
    assign out1 = {1'b0, in1} + 2'd1;

endmodule

