// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Jan 30 14:35:15 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_LessThan_1U_78_1( in1, out1 );

    input [2:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_hub_LessThan_1U_78_1/qkv_macro_handler_hub_LessThan_1U_78_1_thread_1
    assign out1 = (in1[2] ^ in1 < 3'd3);

endmodule

