// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 16:35:13 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_N_Muxb_1_2_97_4( in2, ctrl1, out1 );

    input in2;
    input ctrl1;
    output out1;
    reg out1;

    
    // rtl_process:qkv_macro_handler_hub_N_Muxb_1_2_97_4/qkv_macro_handler_hub_N_Muxb_1_2_97_4_thread_1
    always @*
      begin : qkv_macro_handler_hub_N_Muxb_1_2_97_4_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = 1'b1;
            end
          default: 
            begin
              out1 = in2;
            end
        endcase
      end

endmodule


