// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 14:52:37 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Add_5Ux1U_6U_1( in2, in1, out1 );

    input [4:0] in2;
    input in1;
    output [5:0] out1;

    
    // rtl_process:qkv_macro_handler_hub_Add_5Ux1U_6U_1/qkv_macro_handler_hub_Add_5Ux1U_6U_1_thread_1
    assign out1 = {1'b0, in2} + {5'b00000, in1};

endmodule

