// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Nov 20 15:34:55 2024
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Equal_6Ux1U_1U_1( in2, in1, out1 );

    input [5:0] in2;
    input in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_hub_Equal_6Ux1U_1U_1/qkv_macro_handler_hub_Equal_6Ux1U_1U_1_thread_1
    assign out1 = in2 == {5'b00000, in1};

endmodule

