// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 12:10:03 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_LessThan_1U_149_4( in1, out1 );

    input [7:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_hub_LessThan_1U_149_4/qkv_macro_handler_hub_LessThan_1U_149_4_thread_1
    assign out1 = (in1[7] ^ in1 < 8'd064);

endmodule


