// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Feb  4 13:14:03 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Equal_1U_133_1( in1, out1 );

    input [4:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_hub_Equal_1U_133_1/qkv_macro_handler_hub_Equal_1U_133_1_thread_1
    assign out1 = in1 == 5'd06;

endmodule

