// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Oct 17 11:15:54 2024
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_LessThan_6Sx6S_1U_4( in2, in1, out1 );

    input [5:0] in2;
    input [5:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_hub_LessThan_6Sx6S_1U_4/qkv_macro_handler_hub_LessThan_6Sx6S_1U_4_thread_1
    assign out1 = (in2 < in1 ^ (in1[5] ^ in2[5]));

endmodule

