// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 15:56:55 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Equal_1U_47_4( in1, out1 );

    input [4:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_hub_Equal_1U_47_4/qkv_macro_handler_hub_Equal_1U_47_4_thread_1
    assign out1 = in1 == 5'd07;

endmodule


