// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Feb  4 15:03:20 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Equal_1U_132_1( in1, out1 );

    input [5:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_hub_Equal_1U_132_1/qkv_macro_handler_hub_Equal_1U_132_1_thread_1
    assign out1 = in1 == 6'd05;

endmodule

