// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Feb  4 15:03:18 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Add_6U_144_4( in1, out1 );

    input [4:0] in1;
    output [5:0] out1;

    
    // rtl_process:qkv_macro_handler_hub_Add_6U_144_4/qkv_macro_handler_hub_Add_6U_144_4_thread_1
    assign out1 = {1'b0, in1} + 6'd01;

endmodule


