// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Jan 30 22:18:10 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Add_6Sx4U_7S_1( in2, in1, out1 );

    input [5:0] in2;
    input [3:0] in1;
    output [6:0] out1;

    
    // rtl_process:qkv_macro_handler_hub_Add_6Sx4U_7S_1/qkv_macro_handler_hub_Add_6Sx4U_7S_1_thread_1
    assign out1 = {in2[5], in2} + {3'b000, in1};

endmodule

