// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Oct 30 16:10:55 2024
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Add_1Ux1U_2U_4( in2, in1, out1 );

    input in2;
    input in1;
    output [1:0] out1;

    
    // rtl_process:qkv_macro_handler_hub_Add_1Ux1U_2U_4/qkv_macro_handler_hub_Add_1Ux1U_2U_4_thread_1
    assign out1 = {1'b0, in2} + {1'b0, in1};

endmodule

