// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Feb  4 13:13:57 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Add_32Sx1U_32S_4( in2, in1, out1 );

    input [31:0] in2;
    input in1;
    output [31:0] out1;

    
    // rtl_process:qkv_macro_handler_hub_Add_32Sx1U_32S_4/qkv_macro_handler_hub_Add_32Sx1U_32S_4_thread_1
    assign out1 = in2 + {31'b0000000000000000000000000000000, in1};

endmodule

