// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 15:55:26 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Add_32Sx4U_32S_1( in2, in1, out1 );

    input [31:0] in2;
    input [3:0] in1;
    output [31:0] out1;

    
    // rtl_process:qkv_macro_handler_hub_Add_32Sx4U_32S_1/qkv_macro_handler_hub_Add_32Sx4U_32S_1_thread_1
    assign out1 = in2 + {28'b0000000000000000000000000000, in1};

endmodule

