// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 17:21:56 2025
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Equal_1U_140_1( in1, out1 );

    input [5:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_hub_Equal_1U_140_1/qkv_macro_handler_hub_Equal_1U_140_1_thread_1
    assign out1 = in1 == 6'd56;

endmodule

