// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Feb  4 15:07:54 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Add_5U_52_4( in1, out1 );

    input [3:0] in1;
    output [4:0] out1;

    
    // rtl_process:qkt_macro_handler_hub_Add_5U_52_4/qkt_macro_handler_hub_Add_5U_52_4_thread_1
    assign out1 = {1'b0, in1} + 5'd01;

endmodule


