// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Feb  4 13:23:04 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_N_Mux_1_4_127_1( in5, in4, in3, in2, ctrl1, out1 );

    input in5;
    input in4;
    input in3;
    input in2;
    input [1:0] ctrl1;
    output out1;
    reg out1;

    
    // rtl_process:qkt_macro_handler_hub_N_Mux_1_4_127_1/qkt_macro_handler_hub_N_Mux_1_4_127_1_thread_1
    always @*
      begin : qkt_macro_handler_hub_N_Mux_1_4_127_1_thread_1
        case (ctrl1) 
          2'd2: 
            begin
              out1 = in4;
            end
          2'd1: 
            begin
              out1 = in3;
            end
          2'd0: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in5;
            end
        endcase
      end

endmodule

