// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Oct 30 16:16:26 2024
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Mul_32S_73_1( in1, out1 );

    input [31:0] in1;
    output [31:0] out1;

    
    // rtl_process:qkt_macro_handler_hub_Mul_32S_73_1/qkt_macro_handler_hub_Mul_32S_73_1_thread_1
    assign out1 = in1 * 32'd0000000255;

endmodule


