// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 15:20:49 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_gen_busy_r_4( in1, in2, in3, out1 );

    input in1;
    input in2;
    input in3;
    output [2:0] out1;
    wire  ioread003;
    wire  tmp65;
    wire  ioread004;
    wire  tmp66;
    wire  tmp67;
    wire  tmp68;
    wire  tmp69;
    wire  tmp70;
    wire  conv_kernel_qkt_in_gen_busy_conv_kernel_qkt_in_m_data_is_invalid_next;
    wire  gdiv;
    wire  gnew_req;
    wire  tmp73;
    wire  tmp72;
    wire  tmp71;

    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_4/qkt_macro_handler_hub_gen_busy_r_4_thread_1_p16
    assign out1 = {tmp73, {tmp72, tmp71}};
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_4/qkt_macro_handler_hub_gen_busy_r_4_thread_1_p15
    assign tmp73 = gnew_req;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_4/qkt_macro_handler_hub_gen_busy_r_4_thread_1_p14
    assign tmp72 = gdiv;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_4/qkt_macro_handler_hub_gen_busy_r_4_thread_1_p13
    assign tmp71 = conv_kernel_qkt_in_gen_busy_conv_kernel_qkt_in_m_data_is_invalid_next;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_4/qkt_macro_handler_hub_gen_busy_r_4_thread_1_p12
    assign conv_kernel_qkt_in_gen_busy_conv_kernel_qkt_in_m_data_is_invalid_next = tmp70;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_4/qkt_macro_handler_hub_gen_busy_r_4_thread_1_p11
    assign tmp70 = ~gdiv;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_4/qkt_macro_handler_hub_gen_busy_r_4_thread_1_p10
    assign gdiv = in1 & tmp69;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_4/qkt_macro_handler_hub_gen_busy_r_4_thread_1_p9
    assign tmp69 = tmp68;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_4/qkt_macro_handler_hub_gen_busy_r_4_thread_1_p8
    assign tmp68 = ~tmp67;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_4/qkt_macro_handler_hub_gen_busy_r_4_thread_1_p7
    assign tmp67 = gnew_req;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_4/qkt_macro_handler_hub_gen_busy_r_4_thread_1_p6
    assign gnew_req = ioread004 & tmp66;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_4/qkt_macro_handler_hub_gen_busy_r_4_thread_1_p5
    assign tmp66 = ioread003 | tmp65;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_4/qkt_macro_handler_hub_gen_busy_r_4_thread_1_p4
    assign tmp65 = in1;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_4/qkt_macro_handler_hub_gen_busy_r_4_thread_1_p3
    assign ioread004 = in2;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_4/qkt_macro_handler_hub_gen_busy_r_4_thread_1_p2
    assign ioread003 = in3;

endmodule


