// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Oct 28 11:05:07 2024
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_N_Mux_32_4_108_4( in5, in4, in3, in2, ctrl1, out1 );

    input [31:0] in5;
    input [31:0] in4;
    input [31:0] in3;
    input [31:0] in2;
    input [1:0] ctrl1;
    output [31:0] out1;
    reg [31:0] out1;

    
    // rtl_process:qkt_macro_handler_hub_N_Mux_32_4_108_4/qkt_macro_handler_hub_N_Mux_32_4_108_4_thread_1
    always @*
      begin : qkt_macro_handler_hub_N_Mux_32_4_108_4_thread_1
        case (ctrl1) 
          2'd2: 
            begin
              out1 = in4;
            end
          2'd1: 
            begin
              out1 = in3;
            end
          2'd0: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in5;
            end
        endcase
      end

endmodule


