// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Oct 28 11:05:07 2024
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Equal_1U_9_4( in1, out1 );

    input [5:0] in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_hub_Equal_1U_9_4/qkt_macro_handler_hub_Equal_1U_9_4_thread_1
    assign out1 = in1 == 6'd48;

endmodule


