// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 17:32:30 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Add_4Ux1U_5U_1( in2, in1, out1 );

    input [3:0] in2;
    input in1;
    output [4:0] out1;

    
    // rtl_process:qkt_macro_handler_hub_Add_4Ux1U_5U_1/qkt_macro_handler_hub_Add_4Ux1U_5U_1_thread_1
    assign out1 = {1'b0, in2} + {4'b0000, in1};

endmodule

