// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 14:29:30 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Minus_8U_8S_1( in1, out1 );

    input [7:0] in1;
    output [7:0] out1;

    
    // rtl_process:qkt_macro_handler_hub_Minus_8U_8S_1/qkt_macro_handler_hub_Minus_8U_8S_1_thread_1
    assign out1 = -in1;

endmodule

