// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 12:51:25 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Equal_1U_83_1( in1, out1 );

    input [5:0] in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_hub_Equal_1U_83_1/qkt_macro_handler_hub_Equal_1U_83_1_thread_1
    assign out1 = in1 == 6'd42;

endmodule

