// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 12:58:10 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Sub_32S_1_1( in1, out1 );

    input [31:0] in1;
    output [31:0] out1;

    
    // rtl_process:qkt_macro_handler_hub_Sub_32S_1_1/qkt_macro_handler_hub_Sub_32S_1_1_thread_1
    assign out1 = in1 - 32'd0000000001;

endmodule


