// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 15:21:10 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_gen_busy_r_1( in1, in2, in3, out1 );

    input in1;
    input in2;
    input in3;
    output [2:0] out1;
    wire  ioread003;
    wire  tmp74;
    wire  ioread004;
    wire  tmp75;
    wire  tmp76;
    wire  tmp77;
    wire  tmp78;
    wire  tmp79;
    wire  conv_kernel_qkt_in_gen_busy_conv_kernel_qkt_in_m_data_is_invalid_next;
    wire  gdiv;
    wire  gnew_req;
    wire  tmp82;
    wire  tmp81;
    wire  tmp80;

    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_1/qkt_macro_handler_hub_gen_busy_r_1_thread_1_p16
    assign out1 = {tmp82, {tmp81, tmp80}};
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_1/qkt_macro_handler_hub_gen_busy_r_1_thread_1_p15
    assign tmp82 = gnew_req;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_1/qkt_macro_handler_hub_gen_busy_r_1_thread_1_p14
    assign tmp81 = gdiv;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_1/qkt_macro_handler_hub_gen_busy_r_1_thread_1_p13
    assign tmp80 = conv_kernel_qkt_in_gen_busy_conv_kernel_qkt_in_m_data_is_invalid_next;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_1/qkt_macro_handler_hub_gen_busy_r_1_thread_1_p12
    assign conv_kernel_qkt_in_gen_busy_conv_kernel_qkt_in_m_data_is_invalid_next = tmp79;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_1/qkt_macro_handler_hub_gen_busy_r_1_thread_1_p11
    assign tmp79 = ~gdiv;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_1/qkt_macro_handler_hub_gen_busy_r_1_thread_1_p10
    assign gdiv = in1 & tmp78;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_1/qkt_macro_handler_hub_gen_busy_r_1_thread_1_p9
    assign tmp78 = tmp77;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_1/qkt_macro_handler_hub_gen_busy_r_1_thread_1_p8
    assign tmp77 = ~tmp76;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_1/qkt_macro_handler_hub_gen_busy_r_1_thread_1_p7
    assign tmp76 = gnew_req;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_1/qkt_macro_handler_hub_gen_busy_r_1_thread_1_p6
    assign gnew_req = ioread004 & tmp75;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_1/qkt_macro_handler_hub_gen_busy_r_1_thread_1_p5
    assign tmp75 = ioread003 | tmp74;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_1/qkt_macro_handler_hub_gen_busy_r_1_thread_1_p4
    assign tmp74 = in1;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_1/qkt_macro_handler_hub_gen_busy_r_1_thread_1_p3
    assign ioread004 = in2;
    
    // rtl_process:qkt_macro_handler_hub_gen_busy_r_1/qkt_macro_handler_hub_gen_busy_r_1_thread_1_p2
    assign ioread003 = in3;

endmodule

