// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 17:25:23 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Add_32Sx8S_32S_4( in2, in1, out1 );

    input [31:0] in2;
    input [7:0] in1;
    output [31:0] out1;

    
    // rtl_process:qkt_macro_handler_hub_Add_32Sx8S_32S_4/qkt_macro_handler_hub_Add_32Sx8S_32S_4_thread_1
    assign out1 = in2 + {{ 24 {in1[7]}}, in1};

endmodule

