// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 12:51:23 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Equal_1U_104_4( in1, out1 );

    input [5:0] in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_hub_Equal_1U_104_4/qkt_macro_handler_hub_Equal_1U_104_4_thread_1
    assign out1 = in1 == 6'd20;

endmodule


