// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Feb  5 10:05:53 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_LeftShift_32S_87_4( in1, out1 );

    input [4:0] in1;
    output [31:0] out1;

    
    // rtl_process:qkt_macro_handler_hub_LeftShift_32S_87_4/qkt_macro_handler_hub_LeftShift_32S_87_4_thread_1
    assign out1 = 32'd0000000001 << in1;

endmodule


