// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 13:10:51 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Equal_2Ux2U_1U_1( in2, in1, out1 );

    input [1:0] in2;
    input [1:0] in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_hub_Equal_2Ux2U_1U_1/qkt_macro_handler_hub_Equal_2Ux2U_1U_1_thread_1
    assign out1 = in2 == in1;

endmodule

