// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 14:28:57 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Equal_6Ux3U_1U_4( in2, in1, out1 );

    input [5:0] in2;
    input [2:0] in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_hub_Equal_6Ux3U_1U_4/qkt_macro_handler_hub_Equal_6Ux3U_1U_4_thread_1
    assign out1 = in2 == {3'b000, in1};

endmodule

