// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Jan 30 13:53:10 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_GreaterThan_32Sx32S_1U_4( in2, in1, out1 );

    input [31:0] in2;
    input [31:0] in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_hub_GreaterThan_32Sx32S_1U_4/qkt_macro_handler_hub_GreaterThan_32Sx32S_1U_4_thread_1
    assign out1 = (in2 > in1 ^ (in1[31] ^ in2[31]));

endmodule


