// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Jan 30 14:43:34 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Equal_1U_86_4( in1, out1 );

    input [5:0] in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_hub_Equal_1U_86_4/qkt_macro_handler_hub_Equal_1U_86_4_thread_1
    assign out1 = in1 == 6'd38;

endmodule


