// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Oct 28 15:34:03 2024
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_N_Mux_32_64_109_1( in65, in64, in63, in62, in61, in60, in59, in58, in57, in56, in55, in54, in53, in52, in51, in50, in49, in48, in47, in46, in45, in44, in43, in42, in41, in40, in39, in38, in37, in36, in35, in34, in33, in32, in31, in30, in29, in28, in27, in26, in25, in24, in23, in22, in21, in20, in19, in18, in17, in16, in15, in14, in13, in12, in11, in10, in9, in8, in7, in6, in5, in4, in3, in2, ctrl1, out1 );

    input [31:0] in65;
    input [31:0] in64;
    input [31:0] in63;
    input [31:0] in62;
    input [31:0] in61;
    input [31:0] in60;
    input [31:0] in59;
    input [31:0] in58;
    input [31:0] in57;
    input [31:0] in56;
    input [31:0] in55;
    input [31:0] in54;
    input [31:0] in53;
    input [31:0] in52;
    input [31:0] in51;
    input [31:0] in50;
    input [31:0] in49;
    input [31:0] in48;
    input [31:0] in47;
    input [31:0] in46;
    input [31:0] in45;
    input [31:0] in44;
    input [31:0] in43;
    input [31:0] in42;
    input [31:0] in41;
    input [31:0] in40;
    input [31:0] in39;
    input [31:0] in38;
    input [31:0] in37;
    input [31:0] in36;
    input [31:0] in35;
    input [31:0] in34;
    input [31:0] in33;
    input [31:0] in32;
    input [31:0] in31;
    input [31:0] in30;
    input [31:0] in29;
    input [31:0] in28;
    input [31:0] in27;
    input [31:0] in26;
    input [31:0] in25;
    input [31:0] in24;
    input [31:0] in23;
    input [31:0] in22;
    input [31:0] in21;
    input [31:0] in20;
    input [31:0] in19;
    input [31:0] in18;
    input [31:0] in17;
    input [31:0] in16;
    input [31:0] in15;
    input [31:0] in14;
    input [31:0] in13;
    input [31:0] in12;
    input [31:0] in11;
    input [31:0] in10;
    input [31:0] in9;
    input [31:0] in8;
    input [31:0] in7;
    input [31:0] in6;
    input [31:0] in5;
    input [31:0] in4;
    input [31:0] in3;
    input [31:0] in2;
    input [5:0] ctrl1;
    output [31:0] out1;
    reg [31:0] out1;

    
    // rtl_process:qkt_macro_handler_hub_N_Mux_32_64_109_1/qkt_macro_handler_hub_N_Mux_32_64_109_1_thread_1
    always @*
      begin : qkt_macro_handler_hub_N_Mux_32_64_109_1_thread_1
        case (ctrl1) 
          6'd62: 
            begin
              out1 = in64;
            end
          6'd61: 
            begin
              out1 = in63;
            end
          6'd60: 
            begin
              out1 = in62;
            end
          6'd59: 
            begin
              out1 = in61;
            end
          6'd58: 
            begin
              out1 = in60;
            end
          6'd57: 
            begin
              out1 = in59;
            end
          6'd56: 
            begin
              out1 = in58;
            end
          6'd55: 
            begin
              out1 = in57;
            end
          6'd54: 
            begin
              out1 = in56;
            end
          6'd53: 
            begin
              out1 = in55;
            end
          6'd52: 
            begin
              out1 = in54;
            end
          6'd51: 
            begin
              out1 = in53;
            end
          6'd50: 
            begin
              out1 = in52;
            end
          6'd49: 
            begin
              out1 = in51;
            end
          6'd48: 
            begin
              out1 = in50;
            end
          6'd47: 
            begin
              out1 = in49;
            end
          6'd46: 
            begin
              out1 = in48;
            end
          6'd45: 
            begin
              out1 = in47;
            end
          6'd44: 
            begin
              out1 = in46;
            end
          6'd43: 
            begin
              out1 = in45;
            end
          6'd42: 
            begin
              out1 = in44;
            end
          6'd41: 
            begin
              out1 = in43;
            end
          6'd40: 
            begin
              out1 = in42;
            end
          6'd39: 
            begin
              out1 = in41;
            end
          6'd38: 
            begin
              out1 = in40;
            end
          6'd37: 
            begin
              out1 = in39;
            end
          6'd36: 
            begin
              out1 = in38;
            end
          6'd35: 
            begin
              out1 = in37;
            end
          6'd34: 
            begin
              out1 = in36;
            end
          6'd33: 
            begin
              out1 = in35;
            end
          6'd32: 
            begin
              out1 = in34;
            end
          6'd31: 
            begin
              out1 = in33;
            end
          6'd30: 
            begin
              out1 = in32;
            end
          6'd29: 
            begin
              out1 = in31;
            end
          6'd28: 
            begin
              out1 = in30;
            end
          6'd27: 
            begin
              out1 = in29;
            end
          6'd26: 
            begin
              out1 = in28;
            end
          6'd25: 
            begin
              out1 = in27;
            end
          6'd24: 
            begin
              out1 = in26;
            end
          6'd23: 
            begin
              out1 = in25;
            end
          6'd22: 
            begin
              out1 = in24;
            end
          6'd21: 
            begin
              out1 = in23;
            end
          6'd20: 
            begin
              out1 = in22;
            end
          6'd19: 
            begin
              out1 = in21;
            end
          6'd18: 
            begin
              out1 = in20;
            end
          6'd17: 
            begin
              out1 = in19;
            end
          6'd16: 
            begin
              out1 = in18;
            end
          6'd15: 
            begin
              out1 = in17;
            end
          6'd14: 
            begin
              out1 = in16;
            end
          6'd13: 
            begin
              out1 = in15;
            end
          6'd12: 
            begin
              out1 = in14;
            end
          6'd11: 
            begin
              out1 = in13;
            end
          6'd10: 
            begin
              out1 = in12;
            end
          6'd09: 
            begin
              out1 = in11;
            end
          6'd08: 
            begin
              out1 = in10;
            end
          6'd07: 
            begin
              out1 = in9;
            end
          6'd06: 
            begin
              out1 = in8;
            end
          6'd05: 
            begin
              out1 = in7;
            end
          6'd04: 
            begin
              out1 = in6;
            end
          6'd03: 
            begin
              out1 = in5;
            end
          6'd02: 
            begin
              out1 = in4;
            end
          6'd01: 
            begin
              out1 = in3;
            end
          6'd00: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in65;
            end
        endcase
      end

endmodule


