// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Jan 30 13:53:12 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_And_1Ux1U_1U_s_1( in2, in1, out1 );

    input in2;
    input in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_hub_And_1Ux1U_1U_s_1/qkt_macro_handler_hub_And_1Ux1U_1U_s_1_thread_1
    assign out1 = in2 & in1;

endmodule

