// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 18:09:39 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_AndReduction_4S_1U_1( in1, out1 );

    input [3:0] in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_hub_AndReduction_4S_1U_1/qkt_macro_handler_hub_AndReduction_4S_1U_1_thread_1
    assign out1 = (&in1);

endmodule

