// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 14:59:20 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Add_7U_129_4( in1, out1 );

    input [6:0] in1;
    output [6:0] out1;

    
    // rtl_process:qkt_macro_handler_hub_Add_7U_129_4/qkt_macro_handler_hub_Add_7U_129_4_thread_1
    assign out1 = in1 + 7'd001;

endmodule

