// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 17:32:30 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Sub_32Sx1U_32S_1( in2, in1, out1 );

    input [31:0] in2;
    input in1;
    output [31:0] out1;

    
    // rtl_process:qkt_macro_handler_hub_Sub_32Sx1U_32S_1/qkt_macro_handler_hub_Sub_32Sx1U_32S_1_thread_1
    assign out1 = in2 - {31'b0000000000000000000000000000000, in1};

endmodule

