// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Oct 28 15:34:04 2024
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_N_Muxb_1_2_41_1( in2, ctrl1, out1 );

    input in2;
    input ctrl1;
    output out1;
    reg out1;

    
    // rtl_process:qkt_macro_handler_hub_N_Muxb_1_2_41_1/qkt_macro_handler_hub_N_Muxb_1_2_41_1_thread_1
    always @*
      begin : qkt_macro_handler_hub_N_Muxb_1_2_41_1_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = 1'b1;
            end
          default: 
            begin
              out1 = in2;
            end
        endcase
      end

endmodule

