// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 21:28:03 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Equal_6Ux1U_1U_4( in2, in1, out1 );

    input [5:0] in2;
    input in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_hub_Equal_6Ux1U_1U_4/qkt_macro_handler_hub_Equal_6Ux1U_1U_4_thread_1
    assign out1 = in2 == {5'b00000, in1};

endmodule

