// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 16:07:02 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Equal_1U_48_1( in1, out1 );

    input [5:0] in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_hub_Equal_1U_48_1/qkt_macro_handler_hub_Equal_1U_48_1_thread_1
    assign out1 = in1 == 6'd01;

endmodule

