// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 18:23:17 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_LessThan_1U_69_1( in1, out1 );

    input [3:0] in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_hub_LessThan_1U_69_1/qkt_macro_handler_hub_LessThan_1U_69_1_thread_1
    assign out1 = (in1[3] ^ in1 < 4'd04);

endmodule


