// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 17:29:53 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Abs_32S_32U_4( in1, out1 );

    input [31:0] in1;
    output [31:0] out1;

    
    // rtl_process:qkt_macro_handler_hub_Abs_32S_32U_4/qkt_macro_handler_hub_Abs_32S_32U_4_thread_1
    assign out1 = (in1[31] ^ in1 < 32'd0000000000) ? -in1 : in1;

endmodule


