// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 12:58:09 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_LeftShift_1Ux5U_32S_4( in2, in1, out1 );

    input in2;
    input [4:0] in1;
    output [31:0] out1;

    
    // rtl_process:qkt_macro_handler_hub_LeftShift_1Ux5U_32S_4/qkt_macro_handler_hub_LeftShift_1Ux5U_32S_4_thread_1
    assign out1 = {31'b0000000000000000000000000000000, in2} << in1;

endmodule

