// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 12:51:23 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_N_Muxb_1_2_63_4( in2, ctrl1, out1 );

    input in2;
    input ctrl1;
    output out1;
    reg out1;

    
    // rtl_process:qkt_macro_handler_hub_N_Muxb_1_2_63_4/qkt_macro_handler_hub_N_Muxb_1_2_63_4_thread_1
    always @*
      begin : qkt_macro_handler_hub_N_Muxb_1_2_63_4_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = 1'b0;
            end
          default: 
            begin
              out1 = in2;
            end
        endcase
      end

endmodule


