// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Oct 10 15:52:17 2024
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Add_3U_47_1( in1, out1 );

    input [1:0] in1;
    output [2:0] out1;

    
    // rtl_process:qkt_macro_handler_hub_Add_3U_47_1/qkt_macro_handler_hub_Add_3U_47_1_thread_1
    assign out1 = {1'b0, in1} + 3'd1;

endmodule

