// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Oct 30 16:16:24 2024
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Sub_5Ux5U_5U_4( in2, in1, out1 );

    input [4:0] in2;
    input [4:0] in1;
    output [4:0] out1;

    
    // rtl_process:qkt_macro_handler_hub_Sub_5Ux5U_5U_4/qkt_macro_handler_hub_Sub_5Ux5U_5U_4_thread_1
    assign out1 = in2 - in1;

endmodule


