// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Feb  4 15:07:55 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_N_Mux_32_2_0_1( in3, in2, ctrl1, out1 );

    input [31:0] in3;
    input [31:0] in2;
    input ctrl1;
    output [31:0] out1;
    reg [31:0] out1;

    
    // rtl_process:qkt_macro_handler_hub_N_Mux_32_2_0_1/qkt_macro_handler_hub_N_Mux_32_2_0_1_thread_1
    always @*
      begin : qkt_macro_handler_hub_N_Mux_32_2_0_1_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in3;
            end
        endcase
      end

endmodule


