// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Nov 20 15:43:20 2024
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Minus_8U_8S_4( in1, out1 );

    input [7:0] in1;
    output [7:0] out1;

    
    // rtl_process:qkt_macro_handler_hub_Minus_8U_8S_4/qkt_macro_handler_hub_Minus_8U_8S_4_thread_1
    assign out1 = -in1;

endmodule


