// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 16:05:27 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Equal_1U_42_4( in1, out1 );

    input [1:0] in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_hub_Equal_1U_42_4/qkt_macro_handler_hub_Equal_1U_42_4_thread_1
    assign out1 = in1 == 2'd3;

endmodule


