// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Nov 20 14:43:54 2024
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_LessThan_1U_62_1( in1, out1 );

    input [3:0] in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_hub_LessThan_1U_35_1/qkt_macro_handler_hub_LessThan_1U_35_1_thread_1
    assign out1 = (in1[3] ^ in1 < 4'd04);

endmodule




