// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Sep 30 18:28:53 2024
// from snax_req_handler.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Not_1U_1U_s_4( in1, out1 );

    input in1;
    output out1;

    
    // rtl_process:snax_req_handler_Not_1U_1U_s_4/snax_req_handler_Not_1U_1U_s_4_thread_1
    assign out1 = !in1;

endmodule




