// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Nov 20 14:32:37 2024
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Equal_1U_23_4( in1, out1 );

    input [5:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_hub_Equal_1U_61_4/qkv_macro_handler_hub_Equal_1U_61_4_thread_1
    assign out1 = in1 == 6'd62;

endmodule




