// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Feb  4 13:22:42 2025
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_N_Mux_8_2_59_4( in2, ctrl1, out1 );

    input [7:0] in2;
    input ctrl1;
    output [7:0] out1;
    reg [7:0] out1;

    
    // rtl_process:qkt_macro_handler_hub_N_Mux_8_2_59_4/qkt_macro_handler_hub_N_Mux_8_2_59_4_thread_1
    always @*
      begin : qkt_macro_handler_hub_N_Mux_8_2_59_4_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = 8'd000;
            end
        endcase
      end

endmodule




