// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Sep 30 18:30:27 2024
// from streamer_handler.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Add_7U_44_4( in1, out1 );

    input [5:0] in1;
    output [6:0] out1;

    
    // rtl_process:streamer_handler_Add_7U_3_4/streamer_handler_Add_7U_3_4_thread_1
    assign out1 = {1'b0, in1} + 7'd001;

endmodule




