// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 16:36:34 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_LeftShift_1Ux6U_64U_4( in2, in1, out1 );

    input in2;
    input [5:0] in1;
    output [63:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_LeftShift_1Ux6U_64U_4/qkt_macro_handler_unit_LeftShift_1Ux6U_64U_4_thread_1
    assign out1 = {63'b000000000000000000000000000000000000000000000000000000000000000, in2} << in1;

endmodule

