// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Feb  5 10:10:48 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Add_7U_161_4( in1, out1 );

    input [5:0] in1;
    output [6:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Add_7U_161_4/qkt_macro_handler_unit_Add_7U_161_4_thread_1
    assign out1 = {1'b0, in1} + 7'd001;

endmodule


