// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Oct 10 15:54:47 2024
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Add_5U_77_4( in1, out1 );

    input [3:0] in1;
    output [4:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Add_5U_77_4/qkt_macro_handler_unit_Add_5U_77_4_thread_1
    assign out1 = {1'b0, in1} + 5'd01;

endmodule


