// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Oct 28 11:20:04 2024
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Add_10U_158_4( in1, out1 );

    input [9:0] in1;
    output [9:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Add_10U_158_4/qkt_macro_handler_unit_Add_10U_158_4_thread_1
    assign out1 = in1 + 10'd0001;

endmodule

