// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 12:23:51 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_gen_busy_r_4( in1, in2, in3, out1 );

    input in1;
    input in2;
    input in3;
    output [2:0] out1;
    wire  ioread052;
    wire  tmp0;
    wire  ioread053;
    wire  tmp1;
    wire  tmp2;
    wire  tmp3;
    wire  tmp4;
    wire  tmp5;
    wire  qkt_quant_param_slave_gen_busy_qkt_quant_param_slave_m_data_is_invalid_next;
    wire  gdiv;
    wire  gnew_req;
    wire  tmp8;
    wire  tmp7;
    wire  tmp6;

    
    // rtl_process:qkt_macro_handler_unit_gen_busy_r_4/qkt_macro_handler_unit_gen_busy_r_4_thread_1_p16
    assign out1 = {tmp8, {tmp7, tmp6}};
    
    // rtl_process:qkt_macro_handler_unit_gen_busy_r_4/qkt_macro_handler_unit_gen_busy_r_4_thread_1_p15
    assign tmp8 = gnew_req;
    
    // rtl_process:qkt_macro_handler_unit_gen_busy_r_4/qkt_macro_handler_unit_gen_busy_r_4_thread_1_p14
    assign tmp7 = gdiv;
    
    // rtl_process:qkt_macro_handler_unit_gen_busy_r_4/qkt_macro_handler_unit_gen_busy_r_4_thread_1_p13
    assign tmp6 = qkt_quant_param_slave_gen_busy_qkt_quant_param_slave_m_data_is_invalid_next;
    
    // rtl_process:qkt_macro_handler_unit_gen_busy_r_4/qkt_macro_handler_unit_gen_busy_r_4_thread_1_p12
    assign qkt_quant_param_slave_gen_busy_qkt_quant_param_slave_m_data_is_invalid_next = tmp5;
    
    // rtl_process:qkt_macro_handler_unit_gen_busy_r_4/qkt_macro_handler_unit_gen_busy_r_4_thread_1_p11
    assign tmp5 = ~gdiv;
    
    // rtl_process:qkt_macro_handler_unit_gen_busy_r_4/qkt_macro_handler_unit_gen_busy_r_4_thread_1_p10
    assign gdiv = in1 & tmp4;
    
    // rtl_process:qkt_macro_handler_unit_gen_busy_r_4/qkt_macro_handler_unit_gen_busy_r_4_thread_1_p9
    assign tmp4 = tmp3;
    
    // rtl_process:qkt_macro_handler_unit_gen_busy_r_4/qkt_macro_handler_unit_gen_busy_r_4_thread_1_p8
    assign tmp3 = ~tmp2;
    
    // rtl_process:qkt_macro_handler_unit_gen_busy_r_4/qkt_macro_handler_unit_gen_busy_r_4_thread_1_p7
    assign tmp2 = gnew_req;
    
    // rtl_process:qkt_macro_handler_unit_gen_busy_r_4/qkt_macro_handler_unit_gen_busy_r_4_thread_1_p6
    assign gnew_req = ioread053 & tmp1;
    
    // rtl_process:qkt_macro_handler_unit_gen_busy_r_4/qkt_macro_handler_unit_gen_busy_r_4_thread_1_p5
    assign tmp1 = ioread052 | tmp0;
    
    // rtl_process:qkt_macro_handler_unit_gen_busy_r_4/qkt_macro_handler_unit_gen_busy_r_4_thread_1_p4
    assign tmp0 = in1;
    
    // rtl_process:qkt_macro_handler_unit_gen_busy_r_4/qkt_macro_handler_unit_gen_busy_r_4_thread_1_p3
    assign ioread053 = in2;
    
    // rtl_process:qkt_macro_handler_unit_gen_busy_r_4/qkt_macro_handler_unit_gen_busy_r_4_thread_1_p2
    assign ioread052 = in3;

endmodule


