// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 12:55:22 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Add_8U_154_4( in1, out1 );

    input [7:0] in1;
    output [7:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Add_8U_154_4/qkt_macro_handler_unit_Add_8U_154_4_thread_1
    assign out1 = in1 + 8'd001;

endmodule


