// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Jan 30 14:33:22 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Add_8U_153_1( in1, out1 );

    input [7:0] in1;
    output [7:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Add_8U_153_1/qkt_macro_handler_unit_Add_8U_153_1_thread_1
    assign out1 = in1 + 8'd001;

endmodule

