// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Jan 30 10:31:37 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_N_Mux_8_2_56_1( in3, in2, ctrl1, out1 );

    input [7:0] in3;
    input [7:0] in2;
    input ctrl1;
    output [7:0] out1;
    reg [7:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_N_Mux_8_2_56_1/qkt_macro_handler_unit_N_Mux_8_2_56_1_thread_1
    always @*
      begin : qkt_macro_handler_unit_N_Mux_8_2_56_1_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in3;
            end
        endcase
      end

endmodule


