// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 16:36:34 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Equal_1U_45_4( in1, out1 );

    input [5:0] in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_unit_Equal_1U_45_4/qkt_macro_handler_unit_Equal_1U_45_4_thread_1
    assign out1 = in1 == 6'd39;

endmodule


