// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 14:33:08 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Or_40Ux36U_40U_4( in2, in1, out1 );

    input [39:0] in2;
    input [35:0] in1;
    output [39:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Or_40Ux36U_40U_4/qkt_macro_handler_unit_Or_40Ux36U_40U_4_thread_1
    assign out1 = in2 | {4'b0000, in1};

endmodule


