// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Jan 30 22:31:48 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Add_1Ux1U_2U_1( in2, in1, out1 );

    input in2;
    input in1;
    output [1:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Add_1Ux1U_2U_1/qkt_macro_handler_unit_Add_1Ux1U_2U_1_thread_1
    assign out1 = {1'b0, in2} + {1'b0, in1};

endmodule

