// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Nov  4 15:03:31 2024
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Add_32Sx12U_32S_1( in2, in1, out1 );

    input [31:0] in2;
    input [11:0] in1;
    output [31:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Add_32Sx12U_32S_1/qkt_macro_handler_unit_Add_32Sx12U_32S_1_thread_1
    assign out1 = in2 + {20'b00000000000000000000, in1};

endmodule

