// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Jan 30 22:31:48 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Sub_6Sx1U_6S_1( in2, in1, out1 );

    input [5:0] in2;
    input in1;
    output [5:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Sub_6Sx1U_6S_1/qkt_macro_handler_unit_Sub_6Sx1U_6S_1_thread_1
    assign out1 = in2 - {5'b00000, in1};

endmodule

