// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Oct 30 16:27:05 2024
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Add_5U_158_4( in1, out1 );

    input [4:0] in1;
    output [4:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Add_5U_158_4/qkt_macro_handler_unit_Add_5U_158_4_thread_1
    assign out1 = in1 + 5'd01;

endmodule

