// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Oct 30 16:25:40 2024
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Add_8Ux1U_8U_1( in2, in1, out1 );

    input [7:0] in2;
    input in1;
    output [7:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Add_8Ux1U_8U_1/qkt_macro_handler_unit_Add_8Ux1U_8U_1_thread_1
    assign out1 = in2 + {7'b0000000, in1};

endmodule

