// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 20:00:54 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_N_MuxB_64_2_142_4( in3, in2, ctrl1, out1 );

    input [63:0] in3;
    input [63:0] in2;
    input ctrl1;
    output [63:0] out1;
    reg [63:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_N_MuxB_64_2_142_4/qkt_macro_handler_unit_N_MuxB_64_2_142_4_thread_1
    always @*
      begin : qkt_macro_handler_unit_N_MuxB_64_2_142_4_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in3;
            end
        endcase
      end

endmodule


