// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Oct 28 15:36:00 2024
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Add_20Sx17U_21S_1( in2, in1, out1 );

    input [19:0] in2;
    input [16:0] in1;
    output [20:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Add_20Sx17U_21S_1/qkt_macro_handler_unit_Add_20Sx17U_21S_1_thread_1
    assign out1 = {in2[19], in2} + {4'b0000, in1};

endmodule

