// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 16:09:28 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Add_1Ux1U_2U_4( in2, in1, out1 );

    input in2;
    input in1;
    output [1:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Add_1Ux1U_2U_4/qkt_macro_handler_unit_Add_1Ux1U_2U_4_thread_1
    assign out1 = {1'b0, in2} + {1'b0, in1};

endmodule

