// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 15:00:21 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_N_Mux_19_2_36_1( in3, in2, ctrl1, out1 );

    input [18:0] in3;
    input [18:0] in2;
    input ctrl1;
    output [18:0] out1;
    reg [18:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_N_Mux_19_2_36_1/qkt_macro_handler_unit_N_Mux_19_2_36_1_thread_1
    always @*
      begin : qkt_macro_handler_unit_N_Mux_19_2_36_1_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in3;
            end
        endcase
      end

endmodule


