// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Nov  4 15:03:31 2024
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Sub_22Sx17U_23S_1( in2, in1, out1 );

    input [21:0] in2;
    input [16:0] in1;
    output [22:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Sub_22Sx17U_23S_1/qkt_macro_handler_unit_Sub_22Sx17U_23S_1_thread_1
    assign out1 = {in2[21], in2} - {6'b000000, in1};

endmodule

