// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 12:55:23 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Minus_17U_18S_1( in1, out1 );

    input [16:0] in1;
    output [17:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Minus_17U_18S_1/qkt_macro_handler_unit_Minus_17U_18S_1_thread_1
    assign out1 = -{1'b0, in1};

endmodule


