// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Oct 17 11:29:09 2024
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Equal_1U_38_1( in1, out1 );

    input [5:0] in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_unit_Equal_1U_38_1/qkt_macro_handler_unit_Equal_1U_38_1_thread_1
    assign out1 = in1 == 6'd25;

endmodule

