// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Feb  6 10:54:31 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_GreaterThan_32Sx8S_1U_1( in2, in1, out1 );

    input [31:0] in2;
    input [7:0] in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_unit_GreaterThan_32Sx8S_1U_1/qkt_macro_handler_unit_GreaterThan_32Sx8S_1U_1_thread_1
    assign out1 = (in2 > {{ 24 {in1[7]}}, in1} ^ (in1[7] ^ in2[31]));

endmodule

