// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Nov  4 15:03:30 2024
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Xor_64U_124_4( in1, out1 );

    input [63:0] in1;
    output [63:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Xor_64U_124_4/qkt_macro_handler_unit_Xor_64U_124_4_thread_1
    assign out1 = in1 ^ 64'd12297829382473034410;

endmodule


