// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Oct 31 11:06:12 2024
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Sub_29Sx17U_30S_1( in2, in1, out1 );

    input [28:0] in2;
    input [16:0] in1;
    output [29:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Sub_29Sx17U_30S_1/qkt_macro_handler_unit_Sub_29Sx17U_30S_1_thread_1
    assign out1 = {in2[28], in2} - {13'b0000000000000, in1};

endmodule

