// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 22:27:21 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Add_30Sx17U_31S_4( in2, in1, out1 );

    input [29:0] in2;
    input [16:0] in1;
    output [30:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Add_30Sx17U_31S_4/qkt_macro_handler_unit_Add_30Sx17U_31S_4_thread_1
    assign out1 = {in2[29], in2} + {14'b00000000000000, in1};

endmodule

