// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Oct 10 16:00:05 2024
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Add_9U_158_4( in1, out1 );

    input [8:0] in1;
    output [8:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Add_9U_158_4/qkt_macro_handler_unit_Add_9U_158_4_thread_1
    assign out1 = in1 + 9'd001;

endmodule

