// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 15:24:52 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Sub_24Sx17U_25S_4( in2, in1, out1 );

    input [23:0] in2;
    input [16:0] in1;
    output [24:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Sub_24Sx17U_25S_4/qkt_macro_handler_unit_Sub_24Sx17U_25S_4_thread_1
    assign out1 = {in2[23], in2} - {8'b00000000, in1};

endmodule

