// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Feb  6 10:54:30 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_N_Mux_1_2_83_4( in2, ctrl1, out1 );

    input in2;
    input ctrl1;
    output out1;
    reg out1;

    
    // rtl_process:qkt_macro_handler_unit_N_Mux_1_2_83_4/qkt_macro_handler_unit_N_Mux_1_2_83_4_thread_1
    always @*
      begin : qkt_macro_handler_unit_N_Mux_1_2_83_4_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = 1'b1;
            end
        endcase
      end

endmodule


