// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Oct 30 16:25:38 2024
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Add_2U_1_4( in1, out1 );

    input in1;
    output [1:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Add_2U_1_4/qkt_macro_handler_unit_Add_2U_1_4_thread_1
    assign out1 = {1'b0, in1} + 2'd1;

endmodule


