// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Oct 10 15:55:15 2024
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Xor_1Ux1U_1U_1( in2, in1, out1 );

    input in2;
    input in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_unit_Xor_1Ux1U_1U_1/qkt_macro_handler_unit_Xor_1Ux1U_1U_1_thread_1
    assign out1 = in2 ^ in1;

endmodule

