// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 10:40:56 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Add_32Sx17U_32S_4( in2, in1, out1 );

    input [31:0] in2;
    input [16:0] in1;
    output [31:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Add_32Sx17U_32S_4/qkt_macro_handler_unit_Add_32Sx17U_32S_4_thread_1
    assign out1 = in2 + {15'b000000000000000, in1};

endmodule

