// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 21:32:11 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_N_Mux_8_2_103_4( in2, ctrl1, out1 );

    input [7:0] in2;
    input ctrl1;
    output [7:0] out1;
    reg [7:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_N_Mux_8_2_103_4/qkt_macro_handler_unit_N_Mux_8_2_103_4_thread_1
    always @*
      begin : qkt_macro_handler_unit_N_Mux_8_2_103_4_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = 8'd000;
            end
        endcase
      end

endmodule


