// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 16:11:06 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Or_60Ux56U_60U_4( in2, in1, out1 );

    input [59:0] in2;
    input [55:0] in1;
    output [59:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Or_60Ux56U_60U_4/qkt_macro_handler_unit_Or_60Ux56U_60U_4_thread_1
    assign out1 = in2 | {4'b0000, in1};

endmodule


