// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 18:51:30 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Add_20Sx17U_21S_4( in2, in1, out1 );

    input [19:0] in2;
    input [16:0] in1;
    output [20:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Add_20Sx17U_21S_4/qkt_macro_handler_unit_Add_20Sx17U_21S_4_thread_1
    assign out1 = {in2[19], in2} + {4'b0000, in1};

endmodule

