// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 12:23:55 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Add_32S_70_4( in1, out1 );

    input [31:0] in1;
    output [31:0] out1;

    
    // rtl_process:qkt_macro_handler_unit_Add_32S_70_4/qkt_macro_handler_unit_Add_32S_70_4_thread_1
    assign out1 = in1 + 32'd0000000001;

endmodule

