// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 16:36:36 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Equal_6Ux2U_1U_1( in2, in1, out1 );

    input [5:0] in2;
    input [1:0] in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_unit_Equal_6Ux2U_1U_1/qkt_macro_handler_unit_Equal_6Ux2U_1U_1_thread_1
    assign out1 = in2 == {4'b0000, in1};

endmodule

