// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Feb  4 13:36:37 2025
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_Not_1U_1U_s_1( in1, out1 );

    input in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_unit_Not_1U_1U_s_1/qkt_macro_handler_unit_Not_1U_1U_s_1_thread_1
    assign out1 = !in1;

endmodule


