// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Oct 30 16:25:41 2024
// from qkt_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkt_macro_handler_unit_LessThan_1U_121_1( in1, out1 );

    input [2:0] in1;
    output out1;

    
    // rtl_process:qkt_macro_handler_unit_LessThan_1U_121_1/qkt_macro_handler_unit_LessThan_1U_121_1_thread_1
    assign out1 = (in1[2] ^ in1 < 3'd2);

endmodule


