// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Nov 20 14:41:15 2024
// from qkt_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkt_macro_handler_hub_Div_32Ux32U_8U_4( in2, in1, out1 );

    input [31:0] in2;
    input [31:0] in1;
    output [7:0] out1;
    wire [31:0] R;
    wire [31:0] N_0;
    wire [31:0] Q_0;
    reg [31:0] R_0;
    wire  S_0;
    wire [32:0] T_0;
    wire [31:0] U_0;
    wire [31:0] N_1;
    wire [31:0] Q_1;
    reg [31:0] R_1;
    wire  S_1;
    wire [32:0] T_1;
    wire [30:0] U_1;
    wire [31:0] N_2;
    wire [31:0] Q_2;
    reg [31:0] R_2;
    wire  S_2;
    wire [32:0] T_2;
    wire [29:0] U_2;
    wire [31:0] N_3;
    wire [31:0] Q_3;
    reg [31:0] R_3;
    wire  S_3;
    wire [32:0] T_3;
    wire [28:0] U_3;
    wire [31:0] N_4;
    wire [31:0] Q_4;
    reg [31:0] R_4;
    wire  S_4;
    wire [32:0] T_4;
    wire [27:0] U_4;
    wire [31:0] N_5;
    wire [31:0] Q_5;
    reg [31:0] R_5;
    wire  S_5;
    wire [32:0] T_5;
    wire [26:0] U_5;
    wire [31:0] N_6;
    wire [31:0] Q_6;
    reg [31:0] R_6;
    wire  S_6;
    wire [32:0] T_6;
    wire [25:0] U_6;
    wire [31:0] N_7;
    wire [31:0] Q_7;
    reg [31:0] R_7;
    wire  S_7;
    wire [32:0] T_7;
    wire [24:0] U_7;
    wire [31:0] N_8;
    wire [31:0] Q_8;
    reg [31:0] R_8;
    wire  S_8;
    wire [32:0] T_8;
    wire [23:0] U_8;
    wire [31:0] N_9;
    wire [31:0] Q_9;
    reg [31:0] R_9;
    wire  S_9;
    wire [32:0] T_9;
    wire [22:0] U_9;
    wire [31:0] N_10;
    wire [31:0] Q_10;
    reg [31:0] R_10;
    wire  S_10;
    wire [32:0] T_10;
    wire [21:0] U_10;
    wire [31:0] N_11;
    wire [31:0] Q_11;
    reg [31:0] R_11;
    wire  S_11;
    wire [32:0] T_11;
    wire [20:0] U_11;
    wire [31:0] N_12;
    wire [31:0] Q_12;
    reg [31:0] R_12;
    wire  S_12;
    wire [32:0] T_12;
    wire [19:0] U_12;
    wire [31:0] N_13;
    wire [31:0] Q_13;
    reg [31:0] R_13;
    wire  S_13;
    wire [32:0] T_13;
    wire [18:0] U_13;
    wire [31:0] N_14;
    wire [31:0] Q_14;
    reg [31:0] R_14;
    wire  S_14;
    wire [32:0] T_14;
    wire [17:0] U_14;
    wire [31:0] N_15;
    wire [31:0] Q_15;
    reg [31:0] R_15;
    wire  S_15;
    wire [32:0] T_15;
    wire [16:0] U_15;
    wire [31:0] N_16;
    wire [31:0] Q_16;
    reg [31:0] R_16;
    wire  S_16;
    wire [32:0] T_16;
    wire [15:0] U_16;
    wire [31:0] N_17;
    wire [31:0] Q_17;
    reg [31:0] R_17;
    wire  S_17;
    wire [32:0] T_17;
    wire [14:0] U_17;
    wire [31:0] N_18;
    wire [31:0] Q_18;
    reg [31:0] R_18;
    wire  S_18;
    wire [32:0] T_18;
    wire [13:0] U_18;
    wire [31:0] N_19;
    wire [31:0] Q_19;
    reg [31:0] R_19;
    wire  S_19;
    wire [32:0] T_19;
    wire [12:0] U_19;
    wire [31:0] N_20;
    wire [31:0] Q_20;
    reg [31:0] R_20;
    wire  S_20;
    wire [32:0] T_20;
    wire [11:0] U_20;
    wire [31:0] N_21;
    wire [31:0] Q_21;
    reg [31:0] R_21;
    wire  S_21;
    wire [32:0] T_21;
    wire [10:0] U_21;
    wire [31:0] N_22;
    wire [31:0] Q_22;
    reg [31:0] R_22;
    wire  S_22;
    wire [32:0] T_22;
    wire [9:0] U_22;
    wire [31:0] N_23;
    wire [31:0] Q_23;
    reg [31:0] R_23;
    wire  S_23;
    wire [32:0] T_23;
    wire [8:0] U_23;
    wire [31:0] N_24;
    wire [31:0] Q_24;
    reg [31:0] R_24;
    wire  S_24;
    wire [32:0] T_24;
    wire [7:0] U_24;
    wire [31:0] N_25;
    wire [31:0] Q_25;
    reg [31:0] R_25;
    wire  S_25;
    wire [32:0] T_25;
    wire [6:0] U_25;
    wire [31:0] N_26;
    wire [31:0] Q_26;
    reg [31:0] R_26;
    wire  S_26;
    wire [32:0] T_26;
    wire [5:0] U_26;
    wire [31:0] N_27;
    wire [31:0] Q_27;
    reg [31:0] R_27;
    wire  S_27;
    wire [32:0] T_27;
    wire [4:0] U_27;
    wire [31:0] N_28;
    wire [31:0] Q_28;
    reg [31:0] R_28;
    wire  S_28;
    wire [32:0] T_28;
    wire [3:0] U_28;
    wire [31:0] N_29;
    wire [31:0] Q_29;
    reg [31:0] R_29;
    wire  S_29;
    wire [32:0] T_29;
    wire [2:0] U_29;
    wire [31:0] N_30;
    wire [31:0] Q_30;
    reg [31:0] R_30;
    wire  S_30;
    wire [32:0] T_30;
    wire [1:0] U_30;
    wire [31:0] N_31;
    wire [31:0] Q_31;
    reg [31:0] R_31;
    wire  S_31;
    wire [31:0] D;
    wire [32:0] T_31;
    wire  U_31;
    wire [31:0] R_32;
    wire [31:0] Q_32;
    wire [31:0] N;
    wire [31:0] N_32;
    wire [31:0] Q;

    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p200
    assign out1 = Q[7:0];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p199
    assign N_32 = N;
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p198
    assign Q_32 = N_32;
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p197
    assign R_32 = 32'd0000000000;
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p196
    assign U_31 = N_32[31];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p195
    assign T_31 = {32'b00000000000000000000000000000000, U_31} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p194
    assign S_31 = T_31[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p193
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p193
        case (S_31) 
          1'b1: 
            begin
              R_31 = {31'b0000000000000000000000000000000, U_31};
            end
          default: 
            begin
              R_31 = T_31[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p192
    assign Q_31 = {Q_32[30:0], S_31};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p191
    assign N_31 = {N_32[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p190
    assign U_30 = {R_31[0], N_31[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p189
    assign T_30 = {31'b0000000000000000000000000000000, U_30} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p188
    assign S_30 = T_30[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p187
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p187
        case (S_30) 
          1'b1: 
            begin
              R_30 = {30'b000000000000000000000000000000, U_30};
            end
          default: 
            begin
              R_30 = T_30[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p186
    assign Q_30 = {Q_31[30:0], S_30};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p185
    assign N_30 = {N_31[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p184
    assign U_29 = {R_30[1:0], N_30[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p183
    assign T_29 = {30'b000000000000000000000000000000, U_29} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p182
    assign S_29 = T_29[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p181
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p181
        case (S_29) 
          1'b1: 
            begin
              R_29 = {29'b00000000000000000000000000000, U_29};
            end
          default: 
            begin
              R_29 = T_29[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p180
    assign Q_29 = {Q_30[30:0], S_29};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p179
    assign N_29 = {N_30[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p178
    assign U_28 = {R_29[2:0], N_29[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p177
    assign T_28 = {29'b00000000000000000000000000000, U_28} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p176
    assign S_28 = T_28[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p175
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p175
        case (S_28) 
          1'b1: 
            begin
              R_28 = {28'b0000000000000000000000000000, U_28};
            end
          default: 
            begin
              R_28 = T_28[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p174
    assign Q_28 = {Q_29[30:0], S_28};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p173
    assign N_28 = {N_29[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p172
    assign U_27 = {R_28[3:0], N_28[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p171
    assign T_27 = {28'b0000000000000000000000000000, U_27} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p170
    assign S_27 = T_27[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p169
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p169
        case (S_27) 
          1'b1: 
            begin
              R_27 = {27'b000000000000000000000000000, U_27};
            end
          default: 
            begin
              R_27 = T_27[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p168
    assign Q_27 = {Q_28[30:0], S_27};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p167
    assign N_27 = {N_28[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p166
    assign U_26 = {R_27[4:0], N_27[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p165
    assign T_26 = {27'b000000000000000000000000000, U_26} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p164
    assign S_26 = T_26[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p163
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p163
        case (S_26) 
          1'b1: 
            begin
              R_26 = {26'b00000000000000000000000000, U_26};
            end
          default: 
            begin
              R_26 = T_26[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p162
    assign Q_26 = {Q_27[30:0], S_26};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p161
    assign N_26 = {N_27[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p160
    assign U_25 = {R_26[5:0], N_26[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p159
    assign T_25 = {26'b00000000000000000000000000, U_25} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p158
    assign S_25 = T_25[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p157
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p157
        case (S_25) 
          1'b1: 
            begin
              R_25 = {25'b0000000000000000000000000, U_25};
            end
          default: 
            begin
              R_25 = T_25[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p156
    assign Q_25 = {Q_26[30:0], S_25};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p155
    assign N_25 = {N_26[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p154
    assign U_24 = {R_25[6:0], N_25[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p153
    assign T_24 = {25'b0000000000000000000000000, U_24} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p152
    assign S_24 = T_24[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p151
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p151
        case (S_24) 
          1'b1: 
            begin
              R_24 = {24'b000000000000000000000000, U_24};
            end
          default: 
            begin
              R_24 = T_24[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p150
    assign Q_24 = {Q_25[30:0], S_24};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p149
    assign N_24 = {N_25[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p148
    assign U_23 = {R_24[7:0], N_24[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p147
    assign T_23 = {24'b000000000000000000000000, U_23} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p146
    assign S_23 = T_23[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p145
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p145
        case (S_23) 
          1'b1: 
            begin
              R_23 = {23'b00000000000000000000000, U_23};
            end
          default: 
            begin
              R_23 = T_23[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p144
    assign Q_23 = {Q_24[30:0], S_23};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p143
    assign N_23 = {N_24[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p142
    assign U_22 = {R_23[8:0], N_23[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p141
    assign T_22 = {23'b00000000000000000000000, U_22} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p140
    assign S_22 = T_22[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p139
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p139
        case (S_22) 
          1'b1: 
            begin
              R_22 = {22'b0000000000000000000000, U_22};
            end
          default: 
            begin
              R_22 = T_22[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p138
    assign Q_22 = {Q_23[30:0], S_22};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p137
    assign N_22 = {N_23[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p136
    assign U_21 = {R_22[9:0], N_22[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p135
    assign T_21 = {22'b0000000000000000000000, U_21} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p134
    assign S_21 = T_21[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p133
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p133
        case (S_21) 
          1'b1: 
            begin
              R_21 = {21'b000000000000000000000, U_21};
            end
          default: 
            begin
              R_21 = T_21[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p132
    assign Q_21 = {Q_22[30:0], S_21};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p131
    assign N_21 = {N_22[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p130
    assign U_20 = {R_21[10:0], N_21[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p129
    assign T_20 = {21'b000000000000000000000, U_20} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p128
    assign S_20 = T_20[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p127
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p127
        case (S_20) 
          1'b1: 
            begin
              R_20 = {20'b00000000000000000000, U_20};
            end
          default: 
            begin
              R_20 = T_20[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p126
    assign Q_20 = {Q_21[30:0], S_20};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p125
    assign N_20 = {N_21[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p124
    assign U_19 = {R_20[11:0], N_20[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p123
    assign T_19 = {20'b00000000000000000000, U_19} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p122
    assign S_19 = T_19[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p121
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p121
        case (S_19) 
          1'b1: 
            begin
              R_19 = {19'b0000000000000000000, U_19};
            end
          default: 
            begin
              R_19 = T_19[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p120
    assign Q_19 = {Q_20[30:0], S_19};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p119
    assign N_19 = {N_20[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p118
    assign U_18 = {R_19[12:0], N_19[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p117
    assign T_18 = {19'b0000000000000000000, U_18} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p116
    assign S_18 = T_18[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p115
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p115
        case (S_18) 
          1'b1: 
            begin
              R_18 = {18'b000000000000000000, U_18};
            end
          default: 
            begin
              R_18 = T_18[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p114
    assign Q_18 = {Q_19[30:0], S_18};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p113
    assign N_18 = {N_19[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p112
    assign U_17 = {R_18[13:0], N_18[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p111
    assign T_17 = {18'b000000000000000000, U_17} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p110
    assign S_17 = T_17[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p109
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p109
        case (S_17) 
          1'b1: 
            begin
              R_17 = {17'b00000000000000000, U_17};
            end
          default: 
            begin
              R_17 = T_17[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p108
    assign Q_17 = {Q_18[30:0], S_17};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p107
    assign N_17 = {N_18[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p106
    assign U_16 = {R_17[14:0], N_17[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p105
    assign T_16 = {17'b00000000000000000, U_16} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p104
    assign S_16 = T_16[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p103
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p103
        case (S_16) 
          1'b1: 
            begin
              R_16 = {16'b0000000000000000, U_16};
            end
          default: 
            begin
              R_16 = T_16[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p102
    assign Q_16 = {Q_17[30:0], S_16};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p101
    assign N_16 = {N_17[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p100
    assign U_15 = {R_16[15:0], N_16[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p99
    assign T_15 = {16'b0000000000000000, U_15} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p98
    assign S_15 = T_15[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p97
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p97
        case (S_15) 
          1'b1: 
            begin
              R_15 = {15'b000000000000000, U_15};
            end
          default: 
            begin
              R_15 = T_15[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p96
    assign Q_15 = {Q_16[30:0], S_15};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p95
    assign N_15 = {N_16[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p94
    assign U_14 = {R_15[16:0], N_15[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p93
    assign T_14 = {15'b000000000000000, U_14} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p92
    assign S_14 = T_14[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p91
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p91
        case (S_14) 
          1'b1: 
            begin
              R_14 = {14'b00000000000000, U_14};
            end
          default: 
            begin
              R_14 = T_14[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p90
    assign Q_14 = {Q_15[30:0], S_14};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p89
    assign N_14 = {N_15[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p88
    assign U_13 = {R_14[17:0], N_14[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p87
    assign T_13 = {14'b00000000000000, U_13} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p86
    assign S_13 = T_13[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p85
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p85
        case (S_13) 
          1'b1: 
            begin
              R_13 = {13'b0000000000000, U_13};
            end
          default: 
            begin
              R_13 = T_13[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p84
    assign Q_13 = {Q_14[30:0], S_13};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p83
    assign N_13 = {N_14[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p82
    assign U_12 = {R_13[18:0], N_13[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p81
    assign T_12 = {13'b0000000000000, U_12} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p80
    assign S_12 = T_12[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p79
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p79
        case (S_12) 
          1'b1: 
            begin
              R_12 = {12'b000000000000, U_12};
            end
          default: 
            begin
              R_12 = T_12[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p78
    assign Q_12 = {Q_13[30:0], S_12};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p77
    assign N_12 = {N_13[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p76
    assign U_11 = {R_12[19:0], N_12[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p75
    assign T_11 = {12'b000000000000, U_11} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p74
    assign S_11 = T_11[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p73
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p73
        case (S_11) 
          1'b1: 
            begin
              R_11 = {11'b00000000000, U_11};
            end
          default: 
            begin
              R_11 = T_11[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p72
    assign Q_11 = {Q_12[30:0], S_11};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p71
    assign N_11 = {N_12[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p70
    assign U_10 = {R_11[20:0], N_11[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p69
    assign T_10 = {11'b00000000000, U_10} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p68
    assign S_10 = T_10[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p67
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p67
        case (S_10) 
          1'b1: 
            begin
              R_10 = {10'b0000000000, U_10};
            end
          default: 
            begin
              R_10 = T_10[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p66
    assign Q_10 = {Q_11[30:0], S_10};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p65
    assign N_10 = {N_11[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p64
    assign U_9 = {R_10[21:0], N_10[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p63
    assign T_9 = {10'b0000000000, U_9} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p62
    assign S_9 = T_9[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p61
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p61
        case (S_9) 
          1'b1: 
            begin
              R_9 = {9'b000000000, U_9};
            end
          default: 
            begin
              R_9 = T_9[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p60
    assign Q_9 = {Q_10[30:0], S_9};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p59
    assign N_9 = {N_10[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p58
    assign U_8 = {R_9[22:0], N_9[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p57
    assign T_8 = {9'b000000000, U_8} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p56
    assign S_8 = T_8[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p55
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p55
        case (S_8) 
          1'b1: 
            begin
              R_8 = {8'b00000000, U_8};
            end
          default: 
            begin
              R_8 = T_8[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p54
    assign Q_8 = {Q_9[30:0], S_8};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p53
    assign N_8 = {N_9[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p52
    assign U_7 = {R_8[23:0], N_8[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p51
    assign T_7 = {8'b00000000, U_7} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p50
    assign S_7 = T_7[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p49
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p49
        case (S_7) 
          1'b1: 
            begin
              R_7 = {7'b0000000, U_7};
            end
          default: 
            begin
              R_7 = T_7[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p48
    assign Q_7 = {Q_8[30:0], S_7};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p47
    assign N_7 = {N_8[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p46
    assign U_6 = {R_7[24:0], N_7[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p45
    assign T_6 = {7'b0000000, U_6} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p44
    assign S_6 = T_6[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p43
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p43
        case (S_6) 
          1'b1: 
            begin
              R_6 = {6'b000000, U_6};
            end
          default: 
            begin
              R_6 = T_6[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p42
    assign Q_6 = {Q_7[30:0], S_6};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p41
    assign N_6 = {N_7[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p40
    assign U_5 = {R_6[25:0], N_6[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p39
    assign T_5 = {6'b000000, U_5} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p38
    assign S_5 = T_5[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p37
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p37
        case (S_5) 
          1'b1: 
            begin
              R_5 = {5'b00000, U_5};
            end
          default: 
            begin
              R_5 = T_5[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p36
    assign Q_5 = {Q_6[30:0], S_5};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p35
    assign N_5 = {N_6[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p34
    assign U_4 = {R_5[26:0], N_5[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p33
    assign T_4 = {5'b00000, U_4} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p32
    assign S_4 = T_4[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p31
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p31
        case (S_4) 
          1'b1: 
            begin
              R_4 = {4'b0000, U_4};
            end
          default: 
            begin
              R_4 = T_4[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p30
    assign Q_4 = {Q_5[30:0], S_4};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p29
    assign N_4 = {N_5[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p28
    assign U_3 = {R_4[27:0], N_4[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p27
    assign T_3 = {4'b0000, U_3} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p26
    assign S_3 = T_3[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p25
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p25
        case (S_3) 
          1'b1: 
            begin
              R_3 = {3'b000, U_3};
            end
          default: 
            begin
              R_3 = T_3[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p24
    assign Q_3 = {Q_4[30:0], S_3};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p23
    assign N_3 = {N_4[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p22
    assign U_2 = {R_3[28:0], N_3[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p21
    assign T_2 = {3'b000, U_2} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p20
    assign S_2 = T_2[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p19
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p19
        case (S_2) 
          1'b1: 
            begin
              R_2 = {2'b00, U_2};
            end
          default: 
            begin
              R_2 = T_2[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p18
    assign Q_2 = {Q_3[30:0], S_2};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p17
    assign N_2 = {N_3[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p16
    assign U_1 = {R_2[29:0], N_2[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p15
    assign T_1 = {2'b00, U_1} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p14
    assign S_1 = T_1[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p13
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p13
        case (S_1) 
          1'b1: 
            begin
              R_1 = {1'b0, U_1};
            end
          default: 
            begin
              R_1 = T_1[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p12
    assign Q_1 = {Q_2[30:0], S_1};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p11
    assign N_1 = {N_2[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p10
    assign U_0 = {R_1[30:0], N_1[31]};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p9
    assign T_0 = {1'b0, U_0} - {1'b0, D};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p8
    assign S_0 = T_0[32];
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p7
    always @*
      begin : qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p7
        case (S_0) 
          1'b1: 
            begin
              R_0 = U_0;
            end
          default: 
            begin
              R_0 = T_0[31:0];
            end
        endcase
      end
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p6
    assign Q_0 = {Q_1[30:0], S_0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p5
    assign N_0 = {N_1[30:0], 1'b0};
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p4
    assign Q = ~Q_0;
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p3
    assign R = R_0;
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p2
    assign D = in1;
    
    // rtl_process:qkt_macro_handler_hub_Div_32Ux32U_8U_4/qkt_macro_handler_hub_Div_32Ux32U_8U_4_thread_1_p1
    assign N = in2;

endmodule




