// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Nov 20 14:34:47 2024
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module streamer_handler_LessThan_1U_9_1( in1, out1 );

    input [5:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_hub_LessThan_1U_11_1/qkv_macro_handler_hub_LessThan_1U_11_1_thread_1
    assign out1 = (in1[5] ^ in1 < 6'd16);

endmodule




