// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Feb  4 12:52:07 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_N_Mux_8_2_17_4( in3, in2, ctrl1, out1 );

    input [7:0] in3;
    input [7:0] in2;
    input ctrl1;
    output [7:0] out1;
    reg [7:0] out1;

    
    // rtl_process:streamer_handler_N_Mux_8_2_17_4/streamer_handler_N_Mux_8_2_17_4_thread_1
    always @*
      begin : streamer_handler_N_Mux_8_2_17_4_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in3;
            end
        endcase
      end

endmodule




