// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Nov 20 14:32:37 2024
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module streamer_handler_Add_2U_29_4( in1, out1 );

    input in1;
    output [1:0] out1;

    
    // rtl_process:qkv_macro_handler_hub_Add_2U_10_4/qkv_macro_handler_hub_Add_2U_10_4_thread_1
    assign out1 = {1'b0, in1} + 2'd1;

endmodule




