// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Nov 20 14:32:37 2024
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module streamer_handler_LessThan_1U_8_4( in1, out1 );

    input [7:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_hub_LessThan_1U_94_4/qkv_macro_handler_hub_LessThan_1U_94_4_thread_1
    assign out1 = (in1[7] ^ in1 < 8'd064);

endmodule




