// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Sep 30 18:33:28 2024
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module streamer_handler_Xor_1Ux1U_1U_4( in2, in1, out1 );

    input in2;
    input in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_unit_Xor_1Ux1U_1U_4/qkv_macro_handler_unit_Xor_1Ux1U_1U_4_thread_1
    assign out1 = in2 ^ in1;

endmodule




