// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Oct  1 17:45:26 2024
// from dimc_detail_model.cc

`timescale 1ps / 1ps


module dimc_macro_Equal_6Ux1U_1U_4( in2, in1, out1 );

    input [5:0] in2;
    input in1;
    output out1;

    
    // rtl_process:dimc_macro_Equal_6Ux1U_1U_4/dimc_macro_Equal_6Ux1U_1U_4_thread_1
    assign out1 = in2 == {5'b00000, in1};

endmodule

