// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Oct  1 17:45:54 2024
// from dimc_detail_model.cc

`timescale 1ps / 1ps


module dimc_macro_Add_5U_83_4( in1, out1 );

    input [4:0] in1;
    output [4:0] out1;

    
    // rtl_process:dimc_macro_Add_5U_83_4/dimc_macro_Add_5U_83_4_thread_1
    assign out1 = in1 + 5'd01;

endmodule

