// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 14:47:32 2025
// from streamer_handler.cc

`timescale 1ps / 1ps


module streamer_handler_N_Mux_8_16_22_4( in17, in16, in15, in14, in13, in12, in11, in10, in9, in8, in7,
    in6, in5, in4, in3, in2, ctrl1, out1 );

    input [7:0] in17;
    input [7:0] in16;
    input [7:0] in15;
    input [7:0] in14;
    input [7:0] in13;
    input [7:0] in12;
    input [7:0] in11;
    input [7:0] in10;
    input [7:0] in9;
    input [7:0] in8;
    input [7:0] in7;
    input [7:0] in6;
    input [7:0] in5;
    input [7:0] in4;
    input [7:0] in3;
    input [7:0] in2;
    input [3:0] ctrl1;
    output [7:0] out1;
    reg [7:0] out1;

    
    // rtl_process:streamer_handler_N_Mux_8_16_22_4/streamer_handler_N_Mux_8_16_22_4_thread_1
    always @*
      begin : streamer_handler_N_Mux_8_16_22_4_thread_1
        case (ctrl1) 
          4'd14: 
            begin
              out1 = in16;
            end
          4'd13: 
            begin
              out1 = in15;
            end
          4'd12: 
            begin
              out1 = in14;
            end
          4'd11: 
            begin
              out1 = in13;
            end
          4'd10: 
            begin
              out1 = in12;
            end
          4'd09: 
            begin
              out1 = in11;
            end
          4'd08: 
            begin
              out1 = in10;
            end
          4'd07: 
            begin
              out1 = in9;
            end
          4'd06: 
            begin
              out1 = in8;
            end
          4'd05: 
            begin
              out1 = in7;
            end
          4'd04: 
            begin
              out1 = in6;
            end
          4'd03: 
            begin
              out1 = in5;
            end
          4'd02: 
            begin
              out1 = in4;
            end
          4'd01: 
            begin
              out1 = in3;
            end
          4'd00: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in17;
            end
        endcase
      end

endmodule




