// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Feb  6 10:59:24 2025
// from dimc_detail_model.cc

`timescale 1ps / 1ps


module dimc_macro_Add_3U_82_4( in1, out1 );

    input [2:0] in1;
    output [2:0] out1;

    
    // rtl_process:dimc_macro_Add_3U_82_4/dimc_macro_Add_3U_82_4_thread_1
    assign out1 = in1 + 3'd1;

endmodule

