// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Oct 30 16:59:59 2024
// from dimc_detail_model.cc

`timescale 1ps / 1ps


module dimc_macro_N_Mux_1_2_42_1( in2, ctrl1, out1 );

    input in2;
    input ctrl1;
    output out1;
    reg out1;

    
    // rtl_process:dimc_macro_N_Mux_1_2_42_1/dimc_macro_N_Mux_1_2_42_1_thread_1
    always @*
      begin : dimc_macro_N_Mux_1_2_42_1_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = 1'b0;
            end
        endcase
      end

endmodule

