// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Oct 28 15:37:01 2024
// from dimc_detail_model.cc

`timescale 1ps / 1ps


module dimc_macro_Mul_8Ux4U_12U_4( in2, in1, out1 );

    input [7:0] in2;
    input [3:0] in1;
    output [11:0] out1;

    
    // rtl_process:dimc_macro_Mul_8Ux4U_12U_4/dimc_macro_Mul_8Ux4U_12U_4_thread_1
    assign out1 = {4'b0000, in2} * {8'b00000000, in1};

endmodule


