// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Feb  6 10:58:36 2025
// from dimc_detail_model.cc

`timescale 1ps / 1ps


module dimc_macro_N_Mux_2_2_32_1( in3, in2, ctrl1, out1 );

    input in3;
    input [1:0] in2;
    input ctrl1;
    output [1:0] out1;
    reg [1:0] out1;

    
    // rtl_process:dimc_macro_N_Mux_2_2_32_1/dimc_macro_N_Mux_2_2_32_1_thread_1
    always @*
      begin : dimc_macro_N_Mux_2_2_32_1_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = {1'b0, in3};
            end
        endcase
      end

endmodule

