// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Oct 17 11:33:49 2024
// from dimc_detail_model.cc

`timescale 1ps / 1ps


module dimc_macro_Equal_1U_68_1( in1, out1 );

    input [5:0] in1;
    output out1;

    
    // rtl_process:dimc_macro_Equal_1U_68_1/dimc_macro_Equal_1U_68_1_thread_1
    assign out1 = in1 == 6'd48;

endmodule

