// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 12:26:53 2025
// from dimc_detail_model.cc

`timescale 1ps / 1ps


module dimc_macro_Equal_6Ux3U_1U_4( in2, in1, out1 );

    input [5:0] in2;
    input [2:0] in1;
    output out1;

    
    // rtl_process:dimc_macro_Equal_6Ux3U_1U_4/dimc_macro_Equal_6Ux3U_1U_4_thread_1
    assign out1 = in2 == {3'b000, in1};

endmodule

