// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 15:28:22 2025
// from dimc_detail_model.cc

`timescale 1ps / 1ps


module dimc_macro_Xor_64U_70_1( in1, out1 );

    input [63:0] in1;
    output [63:0] out1;

    
    // rtl_process:dimc_macro_Xor_64U_70_1/dimc_macro_Xor_64U_70_1_thread_1
    assign out1 = in1 ^ 64'd12297829382473034410;

endmodule

