// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Feb  6 10:58:36 2025
// from dimc_detail_model.cc

`timescale 1ps / 1ps


module dimc_macro_Equal_1U_40_1( in1, out1 );

    input [5:0] in1;
    output out1;

    
    // rtl_process:dimc_macro_Equal_1U_40_1/dimc_macro_Equal_1U_40_1_thread_1
    assign out1 = in1 == 6'd36;

endmodule

