// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 14:34:17 2025
// from dimc_detail_model.cc

`timescale 1ps / 1ps


module dimc_macro_Equal_6Ux2U_1U_1( in2, in1, out1 );

    input [5:0] in2;
    input [1:0] in1;
    output out1;

    
    // rtl_process:dimc_macro_Equal_6Ux2U_1U_1/dimc_macro_Equal_6Ux2U_1U_1_thread_1
    assign out1 = in2 == {4'b0000, in1};

endmodule

