// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 14:01:25 2025
// from dimc_detail_model.cc

`timescale 1ps / 1ps


module dimc_macro_Xor_64Ux64U_64U_4( in2, in1, out1 );

    input [63:0] in2;
    input [63:0] in1;
    output [63:0] out1;

    
    // rtl_process:dimc_macro_Xor_64Ux64U_64U_4/dimc_macro_Xor_64Ux64U_64U_4_thread_1
    assign out1 = in2 ^ in1;

endmodule

