// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 13:18:36 2025
// from dimc_detail_model.cc

`timescale 1ps / 1ps


module dimc_macro_And_1Ux1U_1U_4( in2, in1, out1 );

    input in2;
    input in1;
    output out1;

    
    // rtl_process:dimc_macro_And_1Ux1U_1U_4/dimc_macro_And_1Ux1U_1U_4_thread_1
    assign out1 = in2 & in1;

endmodule


