// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 12:26:54 2025
// from dimc_detail_model.cc

`timescale 1ps / 1ps


module dimc_macro_N_Mux_3_2_34_1( in3, in2, ctrl1, out1 );

    input [2:0] in3;
    input [2:0] in2;
    input ctrl1;
    output [2:0] out1;
    reg [2:0] out1;

    
    // rtl_process:dimc_macro_N_Mux_3_2_34_1/dimc_macro_N_Mux_3_2_34_1_thread_1
    always @*
      begin : dimc_macro_N_Mux_3_2_34_1_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in3;
            end
        endcase
      end

endmodule

