// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Nov 20 14:32:37 2024
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Equal_1U_38_4( in1, out1 );

    input [4:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_hub_Equal_1U_28_4/qkv_macro_handler_hub_Equal_1U_28_4_thread_1
    assign out1 = in1 == 5'd08;

endmodule




