// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Nov 20 14:32:37 2024
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Add_7U_140_4( in1, out1 );

    input [5:0] in1;
    output [6:0] out1;

    
    // rtl_process:qkv_macro_handler_hub_Add_7U_18_4/qkv_macro_handler_hub_Add_7U_18_4_thread_1
    assign out1 = {1'b0, in1} + 7'd001;

endmodule




