// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Nov 20 14:34:48 2024
// from qkv_macro_handler_hub.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_LessThan_1U_147_1( in1, out1 );

    input [6:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_hub_LessThan_1U_35_1/qkv_macro_handler_hub_LessThan_1U_35_1_thread_1
    assign out1 = (in1[6] ^ in1 < 7'd032);

endmodule




