// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Nov 20 14:30:32 2024
// from snax_req_handler.cc

`timescale 1ps / 1ps


module qkv_macro_handler_hub_Xor_1Ux1U_1U_s_1( in2, in1, out1 );

    input in2;
    input in1;
    output out1;

    
    // rtl_process:snax_req_handler_Xor_1Ux1U_1U_1/snax_req_handler_Xor_1Ux1U_1U_1_thread_1
    assign out1 = in2 ^ in1;

endmodule




