// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 13:57:18 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Equal_1U_123_1( in1, out1 );

    input [5:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_unit_Equal_1U_123_1/qkv_macro_handler_unit_Equal_1U_123_1_thread_1
    assign out1 = in1 == 6'd33;

endmodule

