// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 13:30:11 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Or_24Ux20U_24U_4( in2, in1, out1 );

    input [23:0] in2;
    input [19:0] in1;
    output [23:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Or_24Ux20U_24U_4/qkv_macro_handler_unit_Or_24Ux20U_24U_4_thread_1
    assign out1 = in2 | {4'b0000, in1};

endmodule


