// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Jan 30 14:43:26 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Or_44Ux40U_44U_1( in2, in1, out1 );

    input [43:0] in2;
    input [39:0] in1;
    output [43:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Or_44Ux40U_44U_1/qkv_macro_handler_unit_Or_44Ux40U_44U_1_thread_1
    assign out1 = in2 | {4'b0000, in1};

endmodule

