// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 16:33:08 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_5U_96_1( in1, out1 );

    input [3:0] in1;
    output [4:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_5U_96_1/qkv_macro_handler_unit_Add_5U_96_1_thread_1
    assign out1 = {1'b0, in1} + 5'd01;

endmodule

