// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Oct 30 16:14:11 2024
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_LessThan_1U_123_4( in1, out1 );

    input [2:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_unit_LessThan_1U_123_4/qkv_macro_handler_unit_LessThan_1U_123_4_thread_1
    assign out1 = (in1[2] ^ in1 < 3'd2);

endmodule

