// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Oct 17 11:19:34 2024
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_LessThan_34Sx9S_1U_1( in2, in1, out1 );

    input [33:0] in2;
    input [8:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_unit_LessThan_34Sx9S_1U_1/qkv_macro_handler_unit_LessThan_34Sx9S_1U_1_thread_1
    assign out1 = (in2 < {{ 25 {in1[8]}}, in1} ^ (in1[8] ^ in2[33]));

endmodule

