// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 14:28:45 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_3U_1_4( in1, out1 );

    input [1:0] in1;
    output [2:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_3U_1_4/qkv_macro_handler_unit_Add_3U_1_4_thread_1
    assign out1 = {1'b0, in1} + 3'd1;

endmodule


