// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 12:14:47 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Equal_1U_89_4( in1, out1 );

    input [5:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_unit_Equal_1U_89_4/qkv_macro_handler_unit_Equal_1U_89_4_thread_1
    assign out1 = in1 == 6'd43;

endmodule


