// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 16:01:34 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Not_1U_1U_s_4( in1, out1 );

    input in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_unit_Not_1U_1U_s_4/qkv_macro_handler_unit_Not_1U_1U_s_4_thread_1
    assign out1 = !in1;

endmodule


