// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Oct 17 11:23:31 2024
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_9U_162_4( in1, out1 );

    input [8:0] in1;
    output [8:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_9U_162_4/qkv_macro_handler_unit_Add_9U_162_4_thread_1
    assign out1 = in1 + 9'd001;

endmodule

