// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 15:17:04 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_gen_busy_r_4( in1, in2, in3, out1 );

    input in1;
    input in2;
    input in3;
    output [2:0] out1;
    wire  ioread003;
    wire  tmp0;
    wire  ioread004;
    wire  tmp1;
    wire  tmp2;
    wire  tmp3;
    wire  tmp4;
    wire  tmp5;
    wire  qkv_calc_data_slave_gen_busy_qkv_calc_data_slave_m_data_is_invalid_next;
    wire  gdiv_i1;
    wire  gnew_req_i0;
    wire  tmp8;
    wire  tmp7;
    wire  tmp6;

    
    // rtl_process:qkv_macro_handler_unit_gen_busy_r_4/qkv_macro_handler_unit_gen_busy_r_4_thread_1_p16
    assign out1 = {tmp8, {tmp7, tmp6}};
    
    // rtl_process:qkv_macro_handler_unit_gen_busy_r_4/qkv_macro_handler_unit_gen_busy_r_4_thread_1_p15
    assign tmp8 = gnew_req_i0;
    
    // rtl_process:qkv_macro_handler_unit_gen_busy_r_4/qkv_macro_handler_unit_gen_busy_r_4_thread_1_p14
    assign tmp7 = gdiv_i1;
    
    // rtl_process:qkv_macro_handler_unit_gen_busy_r_4/qkv_macro_handler_unit_gen_busy_r_4_thread_1_p13
    assign tmp6 = qkv_calc_data_slave_gen_busy_qkv_calc_data_slave_m_data_is_invalid_next;
    
    // rtl_process:qkv_macro_handler_unit_gen_busy_r_4/qkv_macro_handler_unit_gen_busy_r_4_thread_1_p12
    assign qkv_calc_data_slave_gen_busy_qkv_calc_data_slave_m_data_is_invalid_next = tmp5;
    
    // rtl_process:qkv_macro_handler_unit_gen_busy_r_4/qkv_macro_handler_unit_gen_busy_r_4_thread_1_p11
    assign tmp5 = ~gdiv_i1;
    
    // rtl_process:qkv_macro_handler_unit_gen_busy_r_4/qkv_macro_handler_unit_gen_busy_r_4_thread_1_p10
    assign gdiv_i1 = in1 & tmp4;
    
    // rtl_process:qkv_macro_handler_unit_gen_busy_r_4/qkv_macro_handler_unit_gen_busy_r_4_thread_1_p9
    assign tmp4 = tmp3;
    
    // rtl_process:qkv_macro_handler_unit_gen_busy_r_4/qkv_macro_handler_unit_gen_busy_r_4_thread_1_p8
    assign tmp3 = ~tmp2;
    
    // rtl_process:qkv_macro_handler_unit_gen_busy_r_4/qkv_macro_handler_unit_gen_busy_r_4_thread_1_p7
    assign tmp2 = gnew_req_i0;
    
    // rtl_process:qkv_macro_handler_unit_gen_busy_r_4/qkv_macro_handler_unit_gen_busy_r_4_thread_1_p6
    assign gnew_req_i0 = ioread004 & tmp1;
    
    // rtl_process:qkv_macro_handler_unit_gen_busy_r_4/qkv_macro_handler_unit_gen_busy_r_4_thread_1_p5
    assign tmp1 = ioread003 | tmp0;
    
    // rtl_process:qkv_macro_handler_unit_gen_busy_r_4/qkv_macro_handler_unit_gen_busy_r_4_thread_1_p4
    assign tmp0 = in1;
    
    // rtl_process:qkv_macro_handler_unit_gen_busy_r_4/qkv_macro_handler_unit_gen_busy_r_4_thread_1_p3
    assign ioread004 = in2;
    
    // rtl_process:qkv_macro_handler_unit_gen_busy_r_4/qkv_macro_handler_unit_gen_busy_r_4_thread_1_p2
    assign ioread003 = in3;

endmodule


