// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 16:32:42 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Sub_6Sx1U_6S_4( in2, in1, out1 );

    input [5:0] in2;
    input in1;
    output [5:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Sub_6Sx1U_6S_4/qkv_macro_handler_unit_Sub_6Sx1U_6S_4_thread_1
    assign out1 = in2 - {5'b00000, in1};

endmodule

