// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 18:19:52 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Mul_32Sx32S_64S_4( in2, in1, out1 );

    input [31:0] in2;
    input [31:0] in1;
    output [63:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Mul_32Sx32S_64S_4/qkv_macro_handler_unit_Mul_32Sx32S_64S_4_thread_1
    assign out1 = {{ 32 {in2[31]}}, in2} * {{ 32 {in1[31]}}, in1};

endmodule

