// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 13:06:58 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Minus_17U_18S_4( in1, out1 );

    input [16:0] in1;
    output [17:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Minus_17U_18S_4/qkv_macro_handler_unit_Minus_17U_18S_4_thread_1
    assign out1 = -{1'b0, in1};

endmodule

