// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 16:03:11 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_LessThan_1U_137_1( in1, out1 );

    input [2:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_unit_LessThan_1U_137_1/qkv_macro_handler_unit_LessThan_1U_137_1_thread_1
    assign out1 = (in1[2] ^ in1 < 3'd2);

endmodule


