// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 13:06:58 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_28Sx17U_29S_4( in2, in1, out1 );

    input [27:0] in2;
    input [16:0] in1;
    output [28:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_28Sx17U_29S_4/qkv_macro_handler_unit_Add_28Sx17U_29S_4_thread_1
    assign out1 = {in2[27], in2} + {12'b000000000000, in1};

endmodule

