// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Jan 30 14:43:24 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_21Sx17U_22S_4( in2, in1, out1 );

    input [20:0] in2;
    input [16:0] in1;
    output [21:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_21Sx17U_22S_4/qkv_macro_handler_unit_Add_21Sx17U_22S_4_thread_1
    assign out1 = {in2[20], in2} + {5'b00000, in1};

endmodule

