// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 13:30:12 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_N_MuxB_64_2_144_4( in3, in2, ctrl1, out1 );

    input [63:0] in3;
    input [63:0] in2;
    input ctrl1;
    output [63:0] out1;
    reg [63:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_N_MuxB_64_2_144_4/qkv_macro_handler_unit_N_MuxB_64_2_144_4_thread_1
    always @*
      begin : qkv_macro_handler_unit_N_MuxB_64_2_144_4_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in3;
            end
        endcase
      end

endmodule


