// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 17:21:36 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Sub_6S_125_1( in1, out1 );

    input [5:0] in1;
    output [5:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Sub_6S_125_1/qkv_macro_handler_unit_Sub_6S_125_1_thread_1
    assign out1 = in1 - 6'd01;

endmodule


