// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 12:47:37 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Equal_6Ux5U_1U_1( in2, in1, out1 );

    input [5:0] in2;
    input [4:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_unit_Equal_6Ux5U_1U_1/qkv_macro_handler_unit_Equal_6Ux5U_1U_1_thread_1
    assign out1 = in2 == {1'b0, in1};

endmodule

