// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 12:47:37 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Sub_23Sx17U_24S_1( in2, in1, out1 );

    input [22:0] in2;
    input [16:0] in1;
    output [23:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Sub_23Sx17U_24S_1/qkv_macro_handler_unit_Sub_23Sx17U_24S_1_thread_1
    assign out1 = {in2[22], in2} - {7'b0000000, in1};

endmodule

