// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Oct 17 11:19:34 2024
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_8Ux1U_8U_1( in2, in1, out1 );

    input [7:0] in2;
    input in1;
    output [7:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_8Ux1U_8U_1/qkv_macro_handler_unit_Add_8Ux1U_8U_1_thread_1
    assign out1 = in2 + {7'b0000000, in1};

endmodule

