// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Nov  4 14:59:02 2024
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_24Sx17U_25S_1( in2, in1, out1 );

    input [23:0] in2;
    input [16:0] in1;
    output [24:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_24Sx17U_25S_1/qkv_macro_handler_unit_Add_24Sx17U_25S_1_thread_1
    assign out1 = {in2[23], in2} + {8'b00000000, in1};

endmodule

