// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Oct  1 17:41:36 2024
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Minus_17U_18S_1( in1, out1 );

    input [16:0] in1;
    output [17:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Minus_17U_18S_1/qkv_macro_handler_unit_Minus_17U_18S_1_thread_1
    assign out1 = -{1'b0, in1};

endmodule


