// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 12:47:35 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_16Ux12U_17U_4( in2, in1, out1 );

    input [15:0] in2;
    input [11:0] in1;
    output [16:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_16Ux12U_17U_4/qkv_macro_handler_unit_Add_16Ux12U_17U_4_thread_1
    assign out1 = {1'b0, in2} + {5'b00000, in1};

endmodule


