// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Jan 29 09:52:59 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_2U_2_4( in1, out1 );

    input in1;
    output [1:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_2U_2_4/qkv_macro_handler_unit_Add_2U_2_4_thread_1
    assign out1 = {1'b0, in1} + 2'd1;

endmodule


