// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Oct 30 17:24:46 2024
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Equal_1U_119_1( in1, out1 );

    input [5:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_unit_Equal_1U_119_1/qkv_macro_handler_unit_Equal_1U_119_1_thread_1
    assign out1 = in1 == 6'd22;

endmodule

