// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 14:29:09 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_26Sx17U_27S_1( in2, in1, out1 );

    input [25:0] in2;
    input [16:0] in1;
    output [26:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_26Sx17U_27S_1/qkv_macro_handler_unit_Add_26Sx17U_27S_1_thread_1
    assign out1 = {in2[25], in2} + {10'b0000000000, in1};

endmodule


