// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Feb  3 16:03:09 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_7U_163_4( in1, out1 );

    input [5:0] in1;
    output [6:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_7U_163_4/qkv_macro_handler_unit_Add_7U_163_4_thread_1
    assign out1 = {1'b0, in1} + 7'd001;

endmodule


