// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 22:31:20 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_And_1Ux1U_1U_s_1( in2, in1, out1 );

    input in2;
    input in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_unit_And_1Ux1U_1U_s_1/qkv_macro_handler_unit_And_1Ux1U_1U_s_1_thread_1
    assign out1 = in2 & in1;

endmodule


