// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 12:44:15 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_LeftShift_64U_107_1( in1, out1 );

    input [5:0] in1;
    output [63:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_LeftShift_64U_107_1/qkv_macro_handler_unit_LeftShift_64U_107_1_thread_1
    assign out1 = 64'd00000000000000000001 << in1;

endmodule

