// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Oct 30 17:24:45 2024
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_LessThan_32Sx8S_1U_1( in2, in1, out1 );

    input [31:0] in2;
    input [7:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_unit_LessThan_32Sx8S_1U_1/qkv_macro_handler_unit_LessThan_32Sx8S_1U_1_thread_1
    assign out1 = (in2 < {{ 24 {in1[7]}}, in1} ^ (in1[7] ^ in2[31]));

endmodule


