// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Oct 30 16:14:13 2024
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Equal_1U_109_1( in1, out1 );

    input [5:0] in1;
    output out1;

    
    // rtl_process:qkv_macro_handler_unit_Equal_1U_109_1/qkv_macro_handler_unit_Equal_1U_109_1_thread_1
    assign out1 = in1 == 6'd51;

endmodule

