// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Nov  4 14:59:03 2024
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Or_8Ux4U_8U_1( in2, in1, out1 );

    input [7:0] in2;
    input [3:0] in1;
    output [7:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Or_8Ux4U_8U_1/qkv_macro_handler_unit_Or_8Ux4U_8U_1_thread_1
    assign out1 = in2 | {4'b0000, in1};

endmodule

