// Generated by stratus_hls 23.01-s004  (99406.080430)
// Tue Feb  4 15:03:15 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Or_64Ux60U_64U_4( in2, in1, out1 );

    input [63:0] in2;
    input [59:0] in1;
    output [63:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Or_64Ux60U_64U_4/qkv_macro_handler_unit_Or_64Ux60U_64U_4_thread_1
    assign out1 = in2 | {4'b0000, in1};

endmodule


