// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 12:44:12 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_8Ux1U_8U_4( in2, in1, out1 );

    input [7:0] in2;
    input in1;
    output [7:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_8Ux1U_8U_4/qkv_macro_handler_unit_Add_8Ux1U_8U_4_thread_1
    assign out1 = in2 + {7'b0000000, in1};

endmodule

