// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Jan 30 14:43:27 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_5U_92_1( in1, out1 );

    input [3:0] in1;
    output [4:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_5U_92_1/qkv_macro_handler_unit_Add_5U_92_1_thread_1
    assign out1 = {1'b0, in1} + 5'd01;

endmodule

