// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Nov  4 14:59:00 2024
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_19Sx17U_20S_4( in2, in1, out1 );

    input [18:0] in2;
    input [16:0] in1;
    output [19:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_19Sx17U_20S_4/qkv_macro_handler_unit_Add_19Sx17U_20S_4_thread_1
    assign out1 = {in2[18], in2} + {3'b000, in1};

endmodule

