// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Oct 28 11:01:09 2024
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Sub_31Sx17U_32S_1( in2, in1, out1 );

    input [30:0] in2;
    input [16:0] in1;
    output [31:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Sub_31Sx17U_32S_1/qkv_macro_handler_unit_Sub_31Sx17U_32S_1_thread_1
    assign out1 = {in2[30], in2} - {15'b000000000000000, in1};

endmodule


