// Generated by stratus_hls 23.01-s004  (99406.080430)
// Wed Nov 20 15:39:26 2024
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_N_Mux_31_2_12_1( in3, in2, ctrl1, out1 );

    input [30:0] in3;
    input [30:0] in2;
    input ctrl1;
    output [30:0] out1;
    reg [30:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_N_Mux_31_2_12_1/qkv_macro_handler_unit_N_Mux_31_2_12_1_thread_1
    always @*
      begin : qkv_macro_handler_unit_N_Mux_31_2_12_1_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in3;
            end
        endcase
      end

endmodule

