// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sat Feb  1 17:34:38 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_7U_164_1( in1, out1 );

    input [5:0] in1;
    output [6:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_7U_164_1/qkv_macro_handler_unit_Add_7U_164_1_thread_1
    assign out1 = {1'b0, in1} + 7'd001;

endmodule

