// Generated by stratus_hls 23.01-s004  (99406.080430)
// Sun Feb  2 13:30:11 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_27Sx17U_28S_4( in2, in1, out1 );

    input [26:0] in2;
    input [16:0] in1;
    output [27:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_27Sx17U_28S_4/qkv_macro_handler_unit_Add_27Sx17U_28S_4_thread_1
    assign out1 = {in2[26], in2} + {11'b00000000000, in1};

endmodule

