// Generated by stratus_hls 23.01-s004  (99406.080430)
// Mon Oct 28 13:20:34 2024
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_30Sx17U_31S_4( in2, in1, out1 );

    input [29:0] in2;
    input [16:0] in1;
    output [30:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_30Sx17U_31S_4/qkv_macro_handler_unit_Add_30Sx17U_31S_4_thread_1
    assign out1 = {in2[29], in2} + {14'b00000000000000, in1};

endmodule

