// Generated by stratus_hls 23.01-s004  (99406.080430)
// Fri Jan 31 16:49:05 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Xor_64U_140_1( in1, out1 );

    input [63:0] in1;
    output [63:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Xor_64U_140_1/qkv_macro_handler_unit_Xor_64U_140_1_thread_1
    assign out1 = in1 ^ 64'd12297829382473034410;

endmodule

