// Generated by stratus_hls 23.01-s004  (99406.080430)
// Thu Feb  6 10:44:50 2025
// from qkv_macro_handler_unit.cc

`timescale 1ps / 1ps


module qkv_macro_handler_unit_Add_29Sx17U_30S_4( in2, in1, out1 );

    input [28:0] in2;
    input [16:0] in1;
    output [29:0] out1;

    
    // rtl_process:qkv_macro_handler_unit_Add_29Sx17U_30S_4/qkv_macro_handler_unit_Add_29Sx17U_30S_4_thread_1
    assign out1 = {in2[28], in2} + {13'b0000000000000, in1};

endmodule

